#!/usr/bin/env node

var repl = require('repl');

require.paths.unshift(__dirname);

var Dataset = require('dataset');
var env = require('environment');
var util = require('blist-util');
var sys = require('sys');

util.extend(repl.start('socrata> ').context, {
    Dataset: Dataset,
    env: env,
    sys: sys,
    inspect: sys.inspect
});

