#!/usr/bin/env node

var repl = require('repl');
var sys = require('sys');

require.paths.unshift(__dirname);

var util = require('blist-util');

util.extend(repl.start('socrata> ').context, {
    Dataset: require('dataset'),
    Future: require('future'),

    env: require('environment'),
    sys: sys,
    inspect: sys.inspect
});

