# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: true
# File Options
files:
  include: '**/*.s+(a|c)ss'
# Rule Configuration
rules:
  no-ids: 2
  no-important: 2
  placeholder-in-extend: 0
  nesting-depth:
    - 1
    - max-depth: 10
