FROM socrata/rails3-deps:1.9


ENV APP_BASE_DIR /opt
ENV APP_DIR ${APP_BASE_DIR}/frontend
RUN mkdir -p $APP_DIR && mkdir -p $APP_DIR/tmp && chown socrata:socrata $APP_DIR/tmp
WORKDIR $APP_DIR
COPY . $APP_DIR
COPY docker/ship.d/run /etc/ship.d/run

RUN bundle install

EXPOSE 3000
