#!/bin/sh

errors=0

CATCH_METHOD_INSTANCES=`grep --include='*.js' -RE '\.catch\(' public/javascripts/angular | \
                        grep -vE '\s*//\s*' | \
                        cut -d \: -f 1`
if [ -n "$CATCH_METHOD_INSTANCES" ]; then
  echo "Found instances of '.catch' method invocations:"
  echo "$CATCH_METHOD_INSTANCES\n"
  ((errors++))
fi

DOT_ONLY_INSTANCES=`grep --include='*.js' -RE '\b(it|describe)\.only' karma-test/dataCards/* | \
                    grep -vE '\s*//\s*' | \
                    cut -d \: -f 1`
if [ -n "$DOT_ONLY_INSTANCES" ]; then
  echo "Found instances of '.only' test file restrictions:"
  echo "$DOT_ONLY_INSTANCES\n"
  ((errors++))
fi

### end of static analysis section

if [ $errors -eq 0 ]; then
  exit 0
else
  cat <<EOF
********************************************************************************

                                   (╯°□°)╯︵ ┻━┻
                               P U S H    F A I L E D

Please correct the errors noted above.

If this hook script has detected ONLY false positives, re-run this command with
the --no-verify flag. Update the hook script to avoid these false positives or
document their occurrence in the README if you are able to.

********************************************************************************

EOF
  exit 1
fi
