export const DEFAULT_FILTER_TAB = 'activity';
export const FADE_TRANSIENT_NOTIFICATION_AFTER_MILLISECONDS = 4 * 1000;
export const NOTIFICATIONS_PER_PAGE = 25;
export const THROTTLE_LAZY_LOADING_FOR = 300;
export const TRUNCATE_DESCRIPTION_AFTER = 150;
export const VIEW_METADATA_CHANGED = 'ViewMetadataChanged';
