#!/bin/bash
set -ev

export ZOOKEEPER_HOSTS=${ZOOKEEPER_HOSTS:-"$EXTERNAL_IP:2181"}
export CORESERVICE_URI=${CORESERVICE_URI:-"$EXTERNAL_IP:8080"}

/bin/env_parse ${APP_DIR}/docker/config.yml.j2 ${APP_DIR}/config/config.yml
/bin/env_parse ${APP_DIR}/docker/unicorn.rb.j2 ${APP_DIR}/config/unicorn.rb

/bin/env_parse ${APP_DIR}/docker/environments-config.rb.j2 ${APP_DIR}/config/environment/${RAILS_ENV}.rb

cd ${APP_DIR}
# Using exec to replace the current bash script running with PID1 with Unicorn
# This allows docker to send signals to unicorn, allowing for graceful shutdown
# The unicorn -N option ignores unicorn specific middleware to mute redundant logs.
# RequestLoggerMiddleware will take its place instead and pipe logs to stderr.
exec su socrata -c "HOME=${APP_DIR} bundle exec unicorn -c config/unicorn.rb -N"
