#!/bin/bash

export ZOOKEEPER_HOSTS=${ZOOKEEPER_HOSTS:-"$EXTERNAL_IP:2181"}
export CORESERVICE_URI=${CORESERVICE_URI:-"$EXTERNAL_IP:8080"}
export ACTIVEMQ_HOSTS=${ACTIVEMQ_HOSTS:-"$EXTERNAL_IP"}

export RAILS_ENV=production
export RACK_ENV=production

/bin/env_parse ${APP_DIR}/docker/config.yml.j2 ${APP_DIR}/config/config.yml
/bin/env_parse ${APP_DIR}/docker/thin.yml.j2 ${APP_DIR}/config/thin.yml

cd ${APP_DIR}

exec su socrata -c "HOME=${APP_DIR} bundle exec thin start -C config/thin.yml"
