#!/bin/bash

export ZOOKEEPER_HOSTS=${ZOOKEEPER_HOSTS:-"$EXTERNAL_IP:2181"}
export CORESERVICE_URI=${CORESERVICE_URI:-"$EXTERNAL_IP:8080"}
export ACTIVEMQ_HOSTS=${ACTIVEMQ_HOSTS:-"$EXTERNAL_IP"}

/bin/env_parse ${APP_DIR}/docker/config.yml.j2 ${APP_DIR}/config/config.yml
/bin/env_parse ${APP_DIR}/docker/unicorn.rb.j2 ${APP_DIR}/config/unicorn.rb

cd ${APP_DIR}
# Using exec to replace the current bash script running with PID1 with Unicorn
# This allows docker to send signals to unicorn, allowing for graceful shutdown
exec su socrata -c "HOME=${APP_DIR} unicorn -c config/unicorn.rb"
