--- 
config:
  javascripts:
    cache_dir: cache
  stylesheets:
    cache_dir: cache
javascripts: 
- base:
  - plugins/jquery.sizes.min
  - util/namespace
  - plugins/jquery.cookies.2.1.0.min
- shared-common-all:
  - util/events
  - util/sizing
  - util/util
  - plugins/jquery.tache
  - plugins/jquery.json
  - plugins/jquery.example.min
  - plugins/jqModal
  - plugins/jquery.validate
  - widgets/text-prompt
  - util/alert-override
  - widgets/clipped-text
  - screens/common-layout
  - util/styling
  - plugins/jquery.qtip
  - widgets/blist-alert
  - util/socrata-server
- shared-calendar:
  - plugins/fullcalendar
  - widgets/blist-calendar
- shared-table-editor:
  - data/editors/editor-base
  - data/editors/text-editor
  - plugins/datepicker
  - data/editors/date-editor
  - data/editors/number-editor
  - data/editors/percent-editor
  - data/editors/money-editor
  - data/editors/email-editor
  - data/editors/tag-editor
  - data/editors/url-editor
  - data/editors/phone-editor
  - widgets/combo
  - widgets/values
  - data/editors/flag-editor
  - data/editors/picklist-editor
  - data/editors/checkbox-editor
  - data/editors/stars-editor
  - tiny_mce/tiny_mce_jquery_src
  - data/editors/richtext-editor
  - plugins/ajaxupload.3.0
  - widgets/upload-dialog
  - data/editors/document-editor
  - data/editors/photo-editor
- accounts-show:
  - plugins/ui.core
  - plugins/ui.showedit
  - screens/account-screen
- approval-show:
  - util/urls
  - widgets/dropdown-menu
  - screens/approval-screen
- blists-about:
  - util/urls
  - screens/blist-about-screen
  - screens/attribution-edit
  - widgets/dropdown-menu
- blists-index:
  - plugins/ui.core
  - plugins/ui.draggable
  - util/humane-date
  - util/urls
  - plugins/date
  - data/types
  - data/model
  - data/table
  - widgets/panel-expander
  - widgets/dropdown-menu
  - widgets/selectable-list
  - widgets/sidebar-filter
  - widgets/pagination
  - widgets/info-pane-comments
  - widgets/info-pane-sharing
  - widgets/info-pane-publish
  - screens/blists-screen
  - screens/info-pane
  - screens/meta-tabs
  - screens/attribution-edit
  - widgets/combo
  - widgets/values
- blists-new:
  - plugins/ajaxupload.3.0
  - screens/blist-new-screen
- blists-publish:
  - screens/info-pane
  - plugins/colorpicker
  - plugins/ui.core
  - plugins/ui.draggable
  - plugins/ajaxupload.3.0
  - util/color
  - widgets/reorderable-list
  - screens/blist-publish-screen
- blists-show:
  - plugins/ui.core
  - plugins/ui.draggable
  - plugins/ui.resizable
  - plugins/ui.spinner
  - util/extMouseWheel
  - util/navigation
  - util/inline-login
  - plugins/date
  - plugins/jquery.colorPicker
  - data/types
  - data/model
  - data/table
  - data/table_nav
  - widgets/inline-edit
  - widgets/dropdown-menu
  - widgets/selectable-list
  - widgets/pagination
  - widgets/reorderable-list
  - widgets/column-format
  - widgets/column-totals
  - widgets/info-pane-comments
  - widgets/info-pane-sharing
  - widgets/info-pane-publish
  - widgets/scrollable
  - widgets/dataset-grid
  - screens/filter-screen
  - widgets/visualization
  - screens/info-pane
  - screens/meta-tabs
  - screens/attribution-edit
  - screens/blist-grid-screen
  - screens/signup-screen
  - widgets/combo
  - widgets/values
  - screens/dataset-menu
- communities-show:
  - plugins/jquery.jcarousel
  - plugins/jquery.tagcloud
  - plugins/jquery.history
  - widgets/simple-tab-navigate
  - screens/community-screen
- contacts-index:
  - plugins/jquery.tablesorter
  - plugins/jquery.searchable
  - util/humane-date
  - widgets/panel-expander
  - widgets/selectable-list
  - widgets/combination-list
  - widgets/sidebar-filter
  - screens/contacts-screen
  - screens/info-pane
- data-show:
  - plugins/jquery.jcarousel
  - plugins/jquery.tagcloud
  - plugins/jquery.history
  - widgets/simple-tab-navigate
  - widgets/inline-edit
  - screens/discover-screen
  - util/urls
  - widgets/dropdown-menu
  - screens/nominations-screen
  - widgets/text-prompt
  - plugins/date
  - plugins/ajaxupload.3.0
- homes-show:
  - screens/home-screen
- profiles-show:
  - plugins/jquery.tablesorter
  - plugins/ajaxupload.3.0
  - widgets/selectable-list
  - widgets/combination-list
  - plugins/ui.core
  - plugins/ui.showedit
  - screens/profile-screen
- rpx-return:
  - plugins/ui.core
  - screens/signup-screen
- stats-index:
  - plugins/date
  - data/types
  - data/model
  - data/table
  - screens/stats-screen
- tweetsets:
  - screens/tweetsets-screen
- widgets-show:
  - plugins/jqModal
  - plugins/jquery.example.min
  - plugins/jquery.json
  - plugins/ui.core
  - plugins/ui.draggable
  - plugins/jquery.tache
  - plugins/jquery.validate
  - util/styling
  - plugins/jquery.qtip
  - util/navigation
  - util/util
  - plugins/date
  - data/types
  - data/model
  - data/table
  - data/table_nav
  - widgets/text-prompt
  - widgets/dropdown-menu
  - widgets/scrollable
  - widgets/scrollTabs
  - widgets/inline-edit
  - widgets/dataset-grid
  - widgets/info-pane-publish
  - widgets/visualization
  - screens/external-widget
  - screens/info-pane
  - screens/dataset-menu





stylesheets: 
- base: 
  - base
  - common
  - info-pane
  - layout
  - outer-chrome
  - sidebar
  - widgets
  - modals
  - splash
- base-widgets:
  - base
  - common
  - widgets
  - modals
- base-widgets-preview:
  - base
  - common
  - widgets-preview
- accounts-new:
  - signup-screen
  - form-common
- blists-index:
  - table-core
  - table-blist-list
  - list-screen
  - blists-screen
  - combo
- blists-new:
  - blist-new-screen
  - form-common
- blists-publish:
  - blist-publish-screen
  - colorpicker
  - form-common
- blists-show:
  - table-core
  - table-blist-grid
  - dataset-grid
  - dataset-menus
  - ui.spinner
  - blist-grid-screen
  - form-common
  - combo
- communities-show:
  - community-screen
  - carousel/jquery.jcarousel
  - carousel/discover-carousel-skin
- contacts-index:
  - list-screen
  - contacts-screen
- data-show:
  - nominations-screen
  - form-common
  - discover-screen
  - carousel/jquery.jcarousel
  - carousel/discover-carousel-skin
- rpx-return-login:
  - signup-screen
  - form-common
  - login-rpx-screen
- stats-index:
  - table-core
  - stats-screen
- tweetsets-index:
  - form-common
  - carousel/discover-carousel-skin
  - tweetsets-screen
- widgets-show:
  - table-core
  - dataset-grid
  - dataset-menus
  - external-widget
  - info-pane
  - external-widget-meta
  - form-common
  - combo
  - modals-widget
