---
config:
  javascripts:
    cache_dir: cache
  stylesheets:
    cache_dir: cache
javascripts:
- base:
  - plugins/date
  - plugins/jqModal
  - plugins/jquery.bt
  - plugins/jquery.cookies.2.1.0.min
  - plugins/jquery.example.min
  - plugins/json2
  - plugins/jquery.sizes.min
  - plugins/jquery.tache
  - plugins/jquery.validate
  - plugins/pure
  - plugins/jquery-ui-1.8.5.custom.min
  - plugins/underscore
  - plugins/inheritance
  - util/namespace
  - util/util
  - util/base-model
  - util/compat
  - util/markup
  - util/alert-override
  - util/google-analytics
  - util/user
  - util/dataset/column-container
  - util/dataset/column
  - util/dataset/dataset
  - util/dataset/table
  - util/dataset/calendar
  - util/dataset/chart
  - util/dataset/form
  - util/dataset/map
  - util/styles
  - util/templates
  - util/socrata-server
  - data/types
  - controls/socrata-messaging
  - controls/text-prompt
  - controls/values
  - controls/dropdown-menu
  - screens/all-screens
- shared-common-all:
  - util/events
  - util/sizing
  - controls/clipped-text
  - screens/common-layout
  - controls/scrollable
- shared-calendar:
  - plugins/fullcalendar
  - controls/base-visualization
  - controls/calendars/default-calendar
- shared-table-render:
  - util/humane-number
  - data/model
  - data/table
  - data/table_nav
  - controls/scrollable
  - controls/dataset-grid
- shared-table-editor:
  - util/humane-number
  - data/editors/editor-base
  - data/editors/text-editor
  - plugins/datepicker
  - data/editors/date-editor
  - data/editors/number-editor
  - data/editors/percent-editor
  - data/editors/money-editor
  - data/editors/email-editor
  - data/editors/tag-editor
  - data/editors/url-editor
  - data/editors/phone-editor
  - data/editors/location-editor
  - controls/combo
  - data/editors/flag-editor
  - data/editors/picklist-editor
  - data/editors/checkbox-editor
  - data/editors/stars-editor
  - tiny_mce/tiny_mce_jquery_src
  - data/editors/html-editor
  - plugins/ajaxupload.3.0
  - controls/upload-dialog
  - data/editors/document-editor
  - data/editors/photo-editor
- shared-map:
  - plugins/markerclusterer
  - controls/base-visualization
  - util/color
  - controls/maps/base-map
  - controls/maps/esri-map
  - controls/maps/google-map
  - controls/maps/bing-map
  - controls/maps/heatmap-map
- shared-chart:
  - plugins/highcharts.src
  - plugins/jit
  - util/color
  - controls/base-visualization
  - controls/charts/base-chart
  - controls/charts/highcharts
  - controls/charts/jit
- admin-users:
  - controls/admin-buttons
  - plugins/jquery.uniform
  - plugins/jquery.tablesorter
  - controls/combination-list
  - screens/admin-users-screen
- admin-federations:
  - screens/admin-federations-screen
- admin-metadata:
  - controls/admin-buttons
  - plugins/jquery.uniform
  - screens/admin-metadata-screen
- admin-moderation:
  - plugins/jquery.uniform
  - plugins/jquery.tablesorter
  - controls/combination-list
  - screens/admin-moderation
- admin-sdp-templates:
  - controls/modal-dialogs
  - controls/admin-buttons
  - plugins/jquery.tablesorter
  - controls/combination-list
  - screens/admin-sdp-templates
- admin-sdp-template:
  - plugins/jquery.colorPicker
  - plugins/jquery.uniform
  - plugins/colorpicker
  - plugins/ajaxupload.3.0
  - controls/upload-dialog
  - util/color
  - util/events
  - controls/grid-sidebar/base-sidebar
  - screens/admin-sdp-template
- admin-federation:
  - controls/admin-buttons
  - plugins/jquery.tablesorter
  - controls/combination-list
  - screens/admin-federation-screen
- browse-control:
  - plugins/jquery.uniform
  - plugins/jquery.tagcloud
  - util/events
  - controls/menu
  - controls/dataset-controls
  - controls/expander
  - controls/stars
  - controls/modal-dialogs
  - screens/browse
- screen-nominations:
  - plugins/ajaxupload.3.0
  - util/events
  - util/humane-date
  - controls/modal-dialogs
  - screens/nominations
- widgets-show:
  - plugins/jquery.uniform
  - plugins/jquery.tablesorter
  - controls/full-screen
  - controls/combination-list
  - controls/embed-form
  - util/humane-date
  - util/events
  - controls/modal-dialogs
  - controls/dataset-controls
  - controls/stars
  - controls/menu
  - controls/rich-render-library
  - controls/page-render-type
  - controls/scrollTabs
  - controls/form-inliner
  - screens/widget
- widgets-show-form:
  - plugins/jquery.uniform
- dataset-new:
  - util/serialize
  - plugins/jquery.uniform
  - plugins/ajaxupload.3.0
  - controls/attachments-editor
  - controls/wizard
  - screens/dataset-new
- dataset-show:
  - plugins/jquery.colorPicker
  - plugins/jquery.awesomecomplete
  - plugins/jquery.uniform
  - plugins/jquery.tablesorter
  - plugins/iscroll
  - controls/combination-list
  - util/events
  - util/humane-date
  - util/inline-login
  - util/konami
  - controls/menu
  - controls/wizard-prompt
  - controls/form-inliner
  - controls/modal-dialogs
  - controls/expander
  - controls/feed-list
  - controls/stars
  - controls/grid-sidebar/base-sidebar
  - controls/grid-sidebar/about-dataset
  - controls/grid-sidebar/add-column
  - controls/grid-sidebar/api
  - controls/grid-sidebar/append-replace
  - controls/grid-sidebar/calendar-create
  - controls/grid-sidebar/chart-create
  - controls/grid-sidebar/column-properties
  - controls/grid-sidebar/download-dataset
  - controls/grid-sidebar/embed-sdp
  - controls/grid-sidebar/feed
  - controls/grid-sidebar/filter-dataset
  - controls/grid-sidebar/form-create
  - controls/grid-sidebar/guided-filter
  - controls/grid-sidebar/map-create
  - controls/grid-sidebar/print-dataset
  - controls/grid-sidebar/share-dataset
  - controls/grid-sidebar/show-hide
  - controls/grid-sidebar/subscribe
  - controls/grid-sidebar/signed-dataset
  - controls/grid-sidebar/view-list
  - controls/dataset-controls
  - controls/dataset-email
  - controls/embed-form
  - controls/full-screen
  - controls/format-options
  - controls/rich-render-library
  - controls/fatrow-render-type
  - controls/page-render-type
  - controls/pill-buttons
  - screens/dataset-show
- dataset-edit-metadata:
  - plugins/jquery.uniform
  - plugins/ajaxupload.3.0
  - controls/attachments-editor
  - screens/dataset-edit-metadata
- screen-dataset-thumbnail:
  - plugins/jquery.imgareaselect
  - screens/dataset-thumbnail
- screen-bare-dataset:
  - util/events
  - util/humane-date
  - controls/full-screen
  - screens/dataset-bare
- shared-metrics:
  - plugins/jquery.uniform
  - plugins/daterangepicker.jquery
  - plugins/jquery.tablesorter
  - plugins/highcharts.src
  - controls/charts/metric-charts
  - controls/equiwidth
  - controls/menu
  - controls/metrics-shared
  - controls/metrics
- screen-login-signup:
  - plugins/jquery.uniform
  - screens/login-shared
  - screens/signup-screen
- screen-profile:
  - util/humane-date
  - controls/feed-list
  - screens/profile-screen
- screen-profile-edit:
  - plugins/jquery.uniform
  - plugins/ajaxupload.3.0
  - screens/profile-screen-edit
- homepage-show:
  - screens/homepage-show
- screen-about-interactive:
  - screens/about-interactive


stylesheets:
- chart-screen:
  - chart-screen
- grid-sidebar:
  - jquery.ui.resizable
  - ui.slider
- displays-form:
  - displays-form
- internal-shared:
  - BespinEmbedded
- analytics-shared:
  - jquery-ui-1.8.4.custom
  - ui.daterangepicker
