---
config:
  javascripts:
    cache_dir: cache
  stylesheets:
    cache_dir: cache
javascripts:
- base:
  - plugins/jqModal
  - plugins/jquery.bt
  - plugins/jquery.cookies.2.1.0.min
  - plugins/jquery.example.min
  - plugins/json2
  - plugins/jquery.sizes.min
  - plugins/jquery.tache
  - plugins/jquery.validate.min
  - plugins/pure
  - plugins/ui.core
  - util/underscore-min
  - util/namespace
  - util/util
  - util/compat
  - util/markup
  - util/alert-override
  - util/google-analytics
  - util/dataset
  - widgets/socrata-messaging
  - widgets/text-prompt
  - widgets/values
- shared-common-all:
  - util/events
  - util/sizing
  - widgets/clipped-text
  - screens/common-layout
  - util/socrata-server
  - widgets/scrollable
- shared-calendar:
  - plugins/fullcalendar
  - widgets/blist-calendar
  - widgets/dropdown-menu
- shared-table-render:
  - plugins/ui.draggable
  - plugins/date
  - util/humane-number
  - data/types
  - data/model
  - data/table
  - data/table_nav
  - widgets/scrollable
  - widgets/dropdown-menu
  - widgets/dataset-grid
- shared-table-editor:
  - data/editors/editor-base
  - data/editors/text-editor
  - plugins/datepicker
  - data/editors/date-editor
  - data/editors/number-editor
  - data/editors/percent-editor
  - data/editors/money-editor
  - data/editors/email-editor
  - data/editors/tag-editor
  - data/editors/url-editor
  - data/editors/phone-editor
  - data/editors/location-editor
  - widgets/combo
  - data/editors/flag-editor
  - data/editors/picklist-editor
  - data/editors/checkbox-editor
  - data/editors/stars-editor
  - tiny_mce/tiny_mce_jquery_src
  - data/editors/html-editor
  - plugins/ajaxupload.3.0
  - widgets/upload-dialog
  - data/editors/document-editor
  - data/editors/photo-editor
- shared-map:
  - widgets/base-visualization
  - data/types
  - widgets/maps/base-map
  - widgets/maps/esri-map
  - widgets/maps/google-map
  - widgets/maps/bing-map
- shared-chart:
  - plugins/highcharts.src
  - widgets/base-visualization
  - widgets/charts/base-chart
  - data/types
  - widgets/charts/highcharts
- accounts-show:
  - plugins/ui.showedit
  - screens/account-screen
- approval-show:
  - util/urls
  - widgets/dropdown-menu
  - screens/approval-screen
- admin-sdp-index:
  - screens/admin-sdp-index-screen
- admin-users:
  - screens/admin-users-screen
- blists-about:
  - util/urls
  - plugins/ajaxupload.3.0
  - screens/blist-about-screen
  - screens/attribution-edit
  - screens/metadata-edit
  - widgets/dropdown-menu
- blists-index:
  - plugins/jquery.tablesorter
  - plugins/jquery.jqote.min
  - plugins/ui.draggable
  - plugins/ajaxupload.3.0
  - util/humane-date
  - util/urls
  - plugins/date
  - data/types
  - data/model
  - data/table
  - widgets/combination-list
  - widgets/panel-expander
  - widgets/dropdown-menu
  - widgets/selectable-list
  - widgets/sidebar-filter
  - widgets/pagination
  - widgets/info-pane-comments
  - widgets/info-pane-filtered
  - widgets/info-pane-sharing
  - widgets/info-pane-publish
  - screens/blists-screen
  - screens/info-pane
  - screens/meta-tabs
  - screens/attribution-edit
  - screens/metadata-edit
  - widgets/combo
- blists-new:
  - plugins/ajaxupload.3.0
  - screens/blist-new-screen
- blists-publish:
  - screens/info-pane
  - plugins/colorpicker
  - plugins/ui.draggable
  - plugins/ajaxupload.3.0
  - util/color
  - widgets/reorderable-list
  - screens/blist-publish-screen
- blists-show:
  - plugins/jquery.tablesorter
  - plugins/ui.slider
  - plugins/ui.spinner
  - plugins/ajaxupload.3.0
  - util/extMouseWheel
  - util/navigation
  - util/inline-login
  - plugins/jquery.colorPicker
  - widgets/combination-list
  - widgets/inline-edit
  - widgets/selectable-list
  - widgets/pagination
  - widgets/reorderable-list
  - widgets/column-format
  - widgets/column-totals
  - widgets/info-pane-comments
  - widgets/info-pane-filtered
  - widgets/info-pane-sharing
  - widgets/info-pane-publish
  - screens/filter-screen
  - widgets/visualization
  - screens/info-pane
  - screens/meta-tabs
  - screens/attribution-edit
  - screens/metadata-edit
  - screens/blist-grid-screen
  - screens/signup-screen
  - widgets/combo
  - screens/dataset-menu
  - controls/grid-sidebar/base-sidebar
  - controls/grid-sidebar/location-create
  - widgets/wizard-prompt
- communities-show:
  - plugins/jquery.jcarousel
  - plugins/jquery.tagcloud
  - plugins/jquery.history
  - widgets/simple-tab-navigate
  - screens/community-screen
- contacts-index:
  - plugins/jquery.tablesorter
  - plugins/jquery.searchable
  - util/humane-date
  - widgets/panel-expander
  - widgets/selectable-list
  - widgets/combination-list
  - widgets/sidebar-filter
  - screens/contacts-screen
  - screens/info-pane
- data-show:
  - plugins/jquery.jcarousel
  - plugins/jquery.tagcloud
  - plugins/jquery.history
  - widgets/simple-tab-navigate
  - widgets/inline-edit
  - screens/discover-screen
  - util/urls
  - widgets/dropdown-menu
  - screens/nominations-screen
  - plugins/date
  - plugins/ajaxupload.3.0
- homes-show:
  - screens/home-screen
- profiles-show:
  - plugins/jquery.tablesorter
  - plugins/ajaxupload.3.0
  - widgets/selectable-list
  - widgets/combination-list
  - plugins/ui.showedit
  - screens/profile-screen
- rpx-return:
  - screens/signup-screen
- stats-index:
  - plugins/date
  - data/types
  - data/model
  - data/table
  - screens/stats-screen
- tweetsets:
  - screens/tweetsets-screen
- widgets-show:
  - util/navigation
  - widgets/scrollTabs
  - widgets/inline-edit
  - widgets/info-pane-publish
  - widgets/visualization
  - screens/external-widget
  - screens/info-pane
  - screens/dataset-menu
- widgets-show-new:
  - plugins/ui.effects.custom.min
  - plugins/jquery.uniform
  - plugins/jquery.tablesorter
  - controls/full-screen
  - widgets/combination-list
  - widgets/embed-form
  - util/humane-date
  - util/navigation
  - util/urls
  - controls/dataset-controls
  - controls/stars
  - widgets/menu
  - widgets/scrollTabs
  - widgets/inline-edit
  - widgets/visualization
  - screens/external-widget-new
- widgets-show-new-form:
  - plugins/jquery.uniform
- screen-dataset:
  - plugins/jquery.uniform
  - util/urls
  - widgets/menu
  - widgets/wizard-prompt
  - controls/grid-sidebar/base-sidebar
  - controls/grid-sidebar/form-create
  - controls/grid-sidebar/location-create
  - controls/dataset-controls
  - controls/full-screen
  - screens/dataset



stylesheets: 
- base: 
  - base
  - common
  - info-pane
  - layout
  - outer-chrome
  - sidebar
  - widgets
  - modals
  - splash
- base-widgets:
  - base
  - common
  - widgets
  - modals
- base-widgets-preview:
  - base
  - common
  - widgets-preview
- accounts-new:
  - signup-screen
  - form-common
- blists-index:
  - table-core
  - table-blist-list
  - list-screen
  - blists-screen
  - combo
- blists-index-alt:
  - list-screen
  - blists-alt-screen
- blists-new:
  - blist-new-screen
  - form-common
- blists-about-edit:
  - blist-about-edit-screen
  - form-common
- blists-publish:
  - blist-publish-screen
  - colorpicker
  - form-common
- blists-show:
  - table-blist-grid
  - dataset-menus
  - ui.slider
  - ui.spinner
  - blist-grid-screen
  - grid-sidebar
  - form-common
  - combo
- communities-show:
  - community-screen
  - carousel/jquery.jcarousel
  - carousel/discover-carousel-skin
- contacts-index:
  - list-screen
  - contacts-screen
- data-show:
  - nominations-screen
  - form-common
  - discover-screen
  - carousel/jquery.jcarousel
  - carousel/discover-carousel-skin
- displays-form:
  - displays-form
- rpx-return-login:
  - signup-screen
  - form-common
  - login-rpx-screen
- stats-index:
  - table-core
  - stats-screen
- tweetsets-index:
  - form-common
  - carousel/discover-carousel-skin
  - tweetsets-screen
- widgets-show:
  - dataset-menus
  - external-widget
  - info-pane
  - external-widget-meta
  - form-common
  - combo
  - modals-widget
- internal-shared:
  - internal-screen
  - form-common
  - BespinEmbedded.compressed
- admin-shared:
  - admin-screen
  - form-common
- admin-sdp-index:
  - list-screen
  - admin-sdp-index-screen
