theme:
  colors:
    link: 0071bc
    accent: 20608f
    headers: [ 600, 600, 600, 666, 333 ]
    header:
      line: 06386a
      active:
      - { color: 2e5f8e, position: .286 }
      - { color: 113e6b }
      inactive:
      - { color: 113f6c, position: .286 }
      - { color: 509bdb }
      background:
      - { color: c7c8ca, position: .286 }
      - { color: e6e7e7 }
    carousel:
      background:
      - { color: 2f608f }
      - { color: 0f3c69 }
      text: 0071bc
    buttons:
      hover:
      - { color: 2e5f8e, position: .5 }
      - { color: 285987, position: .5 }
      - { color: 113e6b }
      active:
      - { color: 113f6c }
      - { color: 164471, position: .5 }
      - { color: 2f5f8e, position: .5 }
      - { color: 509bdb }
    summary:
      active: cacaca
      inactive: ececec
      hover: e3ecf7
    welcome:
      border: 9ba5a1
      title:
      - { color: 2f608f, position: .286 }
      - { color: 0f3c69 }
      body: d7ecf9
  images:
    logo:
      source: /stylesheets/images/common/socrata_logo.png
      type: :static
      width: 129px
      height: 34px
    dialog_logo:
      source: /stylesheets/images/common/socrata_logo_light.png
      type: :static
    favicon:
      source: /stylesheets/images/common/favicon.ico
      type: :static
  urls:
    signup:
    - { text: Terms of Service, href: /terms-of-service }
    - { text: Privacy Policy, href: /privacy }
    header:
    - { text: About Socrata, href: http://www.socrata.com/about }
    - { text: Help, href: http://www.getsatisfaction.com/socrata }
    footer:
    - { text: Blog, href: http://blog.socrata.com/, class: rss }
    - { text: Company Info, href: http://www.socrata.com/company-info, rel: nofollow }
    - { text: Terms of Service, href: http://www.socrata.com/terms-of-service, rel: nofollow }
    - { text: Privacy, href: http://www.socrata.com/privacy, rel: nofollow }
    - { text: Contact Us, href: http://www.socrata.com/contact-us, rel: nofollow }

strings.company: Socrata
strings.site_title: Socrata | Making Data Social
strings.discover_header: Discover useful, unique, and unusual datasets created by the community.
strings.copyright_string: '&copy; 2009 Socrata, Inc.'
strings.sign_up: Sign Up
strings.sign_in: Sign In
strings.search_prompt: Search
strings.discover_search_intro: Search for Public Datasets

features.upsell: true
features.revolutionize: true
features.discovery_module: true
features.community_module: true
features.community_creation: true
features.allow_comments: true
features.remember_me: true
features.persistent_analytics: true
features.show_categories: true
features.show_tags: true
