---
# Hey kids. The ordering here determines the ordering for the 'basics first' sort,
# so try to preserve that order when inserting new videos.

- name: sorting-datasets
  title: Sorting Datasets
  type: analyzing
  audience: consumer
  added: 2011-02-10
  length: 1:43 mins
  wistia:
    embedid: e499cf99cb
- name: find-in-dataset
  title: Find in Dataset
  type: analyzing
  audience: consumer
  added: 2011-02-11
  length: 1:00 min
  wistia:
    embedid: 81ee2ffd16
- name: comment
  title: Commenting
  type: sharing
  audience: consumer
  added: 2011-02-25
  length: 0:24 mins
  wistia:
    embedid: da5532febd
- name: basic-filtering
  title: Basic Filtering
  type: analyzing
  audience: consumer
  added: 2011-02-11
  length: 3:27 mins
  wistia:
    embedid: a4aa44a3cb
- name: point-map
  title: Creating a Point Map
  type: maps
  audience: consumer
  added: 2011-02-24
  length: 0:59 mins
  wistia:
    embedid: 474b3838fa
- name: bar-chart
  title: Creating a Bar Chart
  type: charts
  audience: consumer
  added: 2011-02-24
  length: 0:59 mins
  wistia:
    embedid: 39ebfbe6a1
- name: import-dataset
  title: Importing a Dataset
  type: publishing
  audience: publisher
  added: 2011-02-23
  length: 1:08 mins
  wistia:
    embedid: 9034a4cd28
- name: dataset-publication
  title: Publishing a Dataset
  type: publishing
  audience: publisher
  added: 2011-09-26
  length: 1:42 mins
  wistia:
    embedid: e698908422
