# For all gems used in Production, please pin the version
# to at least a major version using the pessimistic operator (e.g. '~> A.B')
#
# Gems used in Test / Development should remain unpinned, with a few exceptions for
# dependencies that we prefer stability over newness (e.g. factory_girl)

source 'https://repo.socrata.com/artifactory/api/gems/rubygems-virtual/'

ruby File.read('.ruby-version').strip

gem 'dotenv-rails', groups: [:development, :test]

gem 'rails', '4.2.8'
gem 'rake', '12.0.0'

# Use postgres as the database for Active Record
gem 'pg', '~> 0.18'

# Cetera access wrapper
gem 'cetera-ruby', '~> 0.1.1', :require => 'cetera'

gem 'jquery-rails', '~> 4.0'

# Use SCSS for stylesheets
gem 'sass-rails', '5.0.6'
gem 'bourbon', '~> 4.2'
gem 'neat', '~> 1.7'
gem 'breakpoint', '~> 2.5'

# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

# Configurable retry of blocks with exponential backoff
gem 'retries', '~> 0.0'

# Logging formatter to make sumo happier
gem 'lograge', '~> 0.3'

# File uploading
gem 'paperclip', '~> 5.0.0'

# Run async jobs in the background
gem 'delayed_job_active_record', '~> 4.1'
gem 'daemons', '~> 1.2'

# Use sanitize to clean html
gem 'sanitize', '~> 4.0'

# Use Unicorn as the app server
gem 'unicorn', '~> 4.9'

# Semantic versioning
gem 'semver2', '~> 3.4'

# Stores the request for use later
gem 'request_store', '~> 1.2'

# Exception notifier - required last so we get airbrake from delayed jobs
gem 'airbrake', '~> 6.2'

# Getty Images' library for making OAuth2 calls to their API.
gem 'ConnectSDK', path: 'vendor/gems/ConnectSDK'

# We use aws-sdk v2 for RDS database migrations
gem 'aws-sdk', '~> 2.0'

# AWS DB migration tasks
gem 'httparty', '~> 0.14'
gem 'decima-ruby', '0.1.0', path: 'vendor/gems/decima-ruby-0.1.0'
# Fetch from git, we need some of the recent bugfixes.
gem 'marathon-api', require: 'marathon', :git => 'https://github.com/otto-de/marathon-api.git', :ref => '0c5e5e0600b298ebb8f47d4007f96ac6bd5c34c6'

# Ops tasks
gem 'net-ping', '~> 1.7'
gem 'mrdialog', '~> 1.0'
gem 'inifile', '~> 3.0'
gem 'diplomat', '~> 0.15'
gem 'git', '~> 1.3'
gem 'clipboard', '~> 1.1'
gem 'jenkins_api_client', '~> 1.4'

# ActiveMQ message processing
gem 'stomp', '1.4.3'

# Testing framework
gem 'rspec-rails', '~> 3.4'

# Feature flag operations.
gem 'signaller-ruby', '~> 0.0', :require => 'signaller'

# ElastiCache auto-discovery for memcached nodes
gem 'dalli-elasticache', '~> 0.2.0'

# Socrata Site Chrome
gem 'socrata_site_chrome', path: '../common/site_chrome'

group :production do
  # Reaps unicorn worker processes under predefined conditions
  gem 'unicorn-worker-killer', '~> 0.4'
end

group :development, :test do
  # Make pry the default in rails console
  gem 'pry-rails'

  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'pry-byebug'
  gem 'pry-remote'
  gem 'pry-stack_explorer'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  # Allows setting up an instance with multiple domains
  gem 'powder'

  gem 'simplecov', require: false
  gem 'simplecov-cobertura', require: false
  gem 'factory_girl_rails', '~> 4.5'
end

group :test do
  gem 'webmock', require: false
  gem 'database_cleaner'

  # integration tests
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'headless'

  gem 'os'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console'

  # Run application with $RAILS_ROOT/Procfile
  gem 'foreman'

  gem 'stackprof', require: false
  gem 'flamegraph'
  gem 'rack-mini-profiler'
end
