development:
  bridge_host: localhost 
  bridge_port: 12345 
  # The orbited host is determined dynamically by looking at the request url and
  # adding "multiuser." as a prefix.
  orbited_port: 9000 
  ie_port: 12345 
  change_ip: 127.0.0.1 
  change_port: 9999

test:
  bridge_host: multiuser
  bridge_port: 12345 
  # The orbited host is determined dynamically by looking at the request url and
  # adding "multiuser." as a prefix.
  orbited_port: 80
  ie_port: 80
  change_ip: 127.0.0.1 
  change_port: 9999

production:
  bridge_host: localhost 
  bridge_port: 12345 
  # The orbited host is determined dynamically by looking at the request url and
  # adding "multiuser." as a prefix.
  orbited_port: 4817 
  # Similarly the exposed bridge server dynamically figures out its host by
  # prefixing "multiuser-ie." as a prefix.
  ie_port: 12345
  change_ip: 127.0.0.1 
  change_port: 9999
