desc 'Run lint and  tests'
task default: %w[lint test]

namespace 'karma' do
  task :deps do
    npm 'run check-dependencies' do |ok, res|
      unless ok
        npm 'install'
      end
    end
  end
  task :runonce do
    npm 'test'
  end
  task :watch do
    npm 'run watch'
  end
end

desc 'Run all JavaScript tests (check prereqs)'
task karma: %w[karma:deps karma:runonce]

desc 'Run all tests and re-run on file change'
task watch: %w[karma:deps karma:watch]

desc 'Run linter'
task :lint do
  npm 'run lint'
end

desc 'Run all tests'
task test: :karma

def npm(command)
  command = "cd karma_config && npm #{command}"
  if block_given?
    sh(command) { |ok, res| yield(ok, res) }
  else
    sh(command)
  end
end

