export const uploadCreate = {
  "resource":{
    "schemas":[],
    "inserted_at":"2017-05-09T23:10:16.339627",
    "id":8325,
    "finished_at":null,
    "filename":"petty_crimes.csv",
    "failed_at":null,
    "created_by":{
       "user_id":"k7tm-2kym",
       "email":"test.user@socrata.com",
       "display_name":"Test User"
    },
    "content_type":null
  },
  "links":{
    "show":"/api/publishing/v1/upload/8325",
    "bytes":"/api/publishing/v1/upload/8325",
    "add_to_revision":"/api/publishing/v1/upload/8325"
  }
};

export const uploadBytes = {
  "resource":{
    "total_rows":9,
    "output_schemas":[
      {
        "output_columns":[
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310263
                }
              ],
              "transform_expr":"to_number(`id`)",
              "output_soql_type":"SoQLNumber",
              "id":285870,
              "completed_at":"2017-05-09T23:10:21"
            },
            "position":0,
            "is_primary_key":false,
            "id":250669,
            "field_name":"id",
            "display_name":"ID",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310264
                }
              ],
              "transform_expr":"`case_number`",
              "output_soql_type":"SoQLText",
              "id":285871,
              "completed_at":"2017-05-09T23:10:21"
            },
            "position":1,
            "is_primary_key":false,
            "id":250670,
            "field_name":"case_number",
            "display_name":"Case Number",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310265
                }
              ],
              "transform_expr":"to_floating_timestamp(`date`)",
              "output_soql_type":"SoQLFloatingTimestamp",
              "id":285872,
              "completed_at":"2017-05-09T23:10:21"
            },
            "position":2,
            "is_primary_key":false,
            "id":250671,
            "field_name":"date",
            "display_name":"Date",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310266
                }
              ],
              "transform_expr":"`block`",
              "output_soql_type":"SoQLText",
              "id":285873,
              "completed_at":"2017-05-09T23:10:20"
            },
            "position":3,
            "is_primary_key":false,
            "id":250672,
            "field_name":"block",
            "display_name":"Block",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310267
                }
              ],
              "transform_expr":"`iucr`",
              "output_soql_type":"SoQLText",
              "id":285874,
              "completed_at":"2017-05-09T23:10:21"
            },
            "position":4,
            "is_primary_key":false,
            "id":250673,
            "field_name":"iucr",
            "display_name":"IUCR",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310268
                }
              ],
              "transform_expr":"`primary_type`",
              "output_soql_type":"SoQLText",
              "id":285875,
              "completed_at":"2017-05-09T23:10:21"
            },
            "position":5,
            "is_primary_key":false,
            "id":250674,
            "field_name":"primary_type",
            "display_name":"Primary Type",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310269
                }
              ],
              "transform_expr":"`description`",
              "output_soql_type":"SoQLText",
              "id":285876,
              "completed_at":null
            },
            "position":6,
            "is_primary_key":false,
            "id":250675,
            "field_name":"description",
            "display_name":"Description",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310270
                }
              ],
              "transform_expr":"`location_description`",
              "output_soql_type":"SoQLText",
              "id":285877,
              "completed_at":null
            },
            "position":7,
            "is_primary_key":false,
            "id":250676,
            "field_name":"location_description",
            "display_name":"Location Description",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310271
                }
              ],
              "transform_expr":"to_boolean(`arrest`)",
              "output_soql_type":"SoQLBoolean",
              "id":285878,
              "completed_at":null
            },
            "position":8,
            "is_primary_key":false,
            "id":250677,
            "field_name":"arrest",
            "display_name":"Arrest",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310272
                }
              ],
              "transform_expr":"to_boolean(`domestic`)",
              "output_soql_type":"SoQLBoolean",
              "id":285879,
              "completed_at":null
            },
            "position":9,
            "is_primary_key":false,
            "id":250678,
            "field_name":"domestic",
            "display_name":"Domestic",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310273
                }
              ],
              "transform_expr":"to_number(`beat`)",
              "output_soql_type":"SoQLNumber",
              "id":285880,
              "completed_at":null
            },
            "position":10,
            "is_primary_key":false,
            "id":250679,
            "field_name":"beat",
            "display_name":"Beat",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310274
                }
              ],
              "transform_expr":"to_number(`district`)",
              "output_soql_type":"SoQLNumber",
              "id":285881,
              "completed_at":null
            },
            "position":11,
            "is_primary_key":false,
            "id":250680,
            "field_name":"district",
            "display_name":"District",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310275
                }
              ],
              "transform_expr":"to_number(`ward`)",
              "output_soql_type":"SoQLNumber",
              "id":285882,
              "completed_at":null
            },
            "position":12,
            "is_primary_key":false,
            "id":250681,
            "field_name":"ward",
            "display_name":"Ward",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310276
                }
              ],
              "transform_expr":"to_number(`community_area`)",
              "output_soql_type":"SoQLNumber",
              "id":285883,
              "completed_at":null
            },
            "position":13,
            "is_primary_key":false,
            "id":250682,
            "field_name":"community_area",
            "display_name":"Community Area",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310277
                }
              ],
              "transform_expr":"`fbi_code`",
              "output_soql_type":"SoQLText",
              "id":285884,
              "completed_at":null
            },
            "position":14,
            "is_primary_key":false,
            "id":250683,
            "field_name":"fbi_code",
            "display_name":"FBI Code",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310278
                }
              ],
              "transform_expr":"to_number(`x_coordinate`)",
              "output_soql_type":"SoQLNumber",
              "id":285885,
              "completed_at":null
            },
            "position":15,
            "is_primary_key":false,
            "id":250684,
            "field_name":"x_coordinate",
            "display_name":"X Coordinate",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310279
                }
              ],
              "transform_expr":"to_number(`y_coordinate`)",
              "output_soql_type":"SoQLNumber",
              "id":285886,
              "completed_at":null
            },
            "position":16,
            "is_primary_key":false,
            "id":250685,
            "field_name":"y_coordinate",
            "display_name":"Y Coordinate",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310280
                }
              ],
              "transform_expr":"to_number(`year`)",
              "output_soql_type":"SoQLNumber",
              "id":285887,
              "completed_at":null
            },
            "position":17,
            "is_primary_key":false,
            "id":250686,
            "field_name":"year",
            "display_name":"Year",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310281
                }
              ],
              "transform_expr":"to_floating_timestamp(`updated_on`)",
              "output_soql_type":"SoQLFloatingTimestamp",
              "id":285888,
              "completed_at":null
            },
            "position":18,
            "is_primary_key":false,
            "id":250687,
            "field_name":"updated_on",
            "display_name":"Updated On",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310282
                }
              ],
              "transform_expr":"to_number(`latitude`)",
              "output_soql_type":"SoQLNumber",
              "id":285889,
              "completed_at":null
            },
            "position":19,
            "is_primary_key":false,
            "id":250688,
            "field_name":"latitude",
            "display_name":"Latitude",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310283
                }
              ],
              "transform_expr":"to_number(`longitude`)",
              "output_soql_type":"SoQLNumber",
              "id":285890,
              "completed_at":null
            },
            "position":20,
            "is_primary_key":false,
            "id":250689,
            "field_name":"longitude",
            "display_name":"Longitude",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310284
                }
              ],
              "transform_expr":"`location`",
              "output_soql_type":"SoQLText",
              "id":285891,
              "completed_at":null
            },
            "position":21,
            "is_primary_key":false,
            "id":250690,
            "field_name":"location",
            "display_name":"Location",
            "description":""
          }
        ],
        "inserted_at":"2017-05-09T23:10:19.128086",
        "input_schema_id":9649,
        "id":9908,
        "error_count":0,
        "created_by":{
          "user_id":"k7tm-2kym",
          "email":"brandon.webster@socrata.com",
          "display_name":"Brandon Webster"
        },
        "completed_at":null
      }
    ],
    "name":null,
    "inserted_at":"2017-05-09T23:10:16.485161",
    "input_columns":[
      {
        "soql_type":"SoQLText",
        "position":0,
        "input_schema_id":9649,
        "id":310263,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"id"
      },
      {
        "soql_type":"SoQLText",
        "position":1,
        "input_schema_id":9649,
        "id":310264,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLText",
        "field_name":"case_number"
      },
      {
        "soql_type":"SoQLText",
        "position":2,
        "input_schema_id":9649,
        "id":310265,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLFloatingTimestamp",
        "field_name":"date"
      },
      {
        "soql_type":"SoQLText",
        "position":3,
        "input_schema_id":9649,
        "id":310266,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLText",
        "field_name":"block"
      },
      {
        "soql_type":"SoQLText",
        "position":4,
        "input_schema_id":9649,
        "id":310267,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLText",
        "field_name":"iucr"
      },
      {
        "soql_type":"SoQLText",
        "position":5,
        "input_schema_id":9649,
        "id":310268,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLText",
        "field_name":"primary_type"
      },
      {
        "soql_type":"SoQLText",
        "position":6,
        "input_schema_id":9649,
        "id":310269,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLText",
        "field_name":"description"
      },
      {
        "soql_type":"SoQLText",
        "position":7,
        "input_schema_id":9649,
        "id":310270,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLText",
        "field_name":"location_description"
      },
      {
        "soql_type":"SoQLText",
        "position":8,
        "input_schema_id":9649,
        "id":310271,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLBoolean",
        "field_name":"arrest"
      },
      {
        "soql_type":"SoQLText",
        "position":9,
        "input_schema_id":9649,
        "id":310272,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLBoolean",
        "field_name":"domestic"
      },
      {
        "soql_type":"SoQLText",
        "position":10,
        "input_schema_id":9649,
        "id":310273,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"beat"
      },
      {
        "soql_type":"SoQLText",
        "position":11,
        "input_schema_id":9649,
        "id":310274,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"district"
      },
      {
        "soql_type":"SoQLText",
        "position":12,
        "input_schema_id":9649,
        "id":310275,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"ward"
      },
      {
        "soql_type":"SoQLText",
        "position":13,
        "input_schema_id":9649,
        "id":310276,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"community_area"
      },
      {
        "soql_type":"SoQLText",
        "position":14,
        "input_schema_id":9649,
        "id":310277,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLText",
        "field_name":"fbi_code"
      },
      {
        "soql_type":"SoQLText",
        "position":15,
        "input_schema_id":9649,
        "id":310278,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"x_coordinate"
      },
      {
        "soql_type":"SoQLText",
        "position":16,
        "input_schema_id":9649,
        "id":310279,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"y_coordinate"
      },
      {
        "soql_type":"SoQLText",
        "position":17,
        "input_schema_id":9649,
        "id":310280,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"year"
      },
      {
        "soql_type":"SoQLText",
        "position":18,
        "input_schema_id":9649,
        "id":310281,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLFloatingTimestamp",
        "field_name":"updated_on"
      },
      {
        "soql_type":"SoQLText",
        "position":19,
        "input_schema_id":9649,
        "id":310282,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"latitude"
      },
      {
        "soql_type":"SoQLText",
        "position":20,
        "input_schema_id":9649,
        "id":310283,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"longitude"
      },
      {
        "soql_type":"SoQLText",
        "position":21,
        "input_schema_id":9649,
        "id":310284,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLText",
        "field_name":"location"
      }
    ],
    "id":9649,
    "created_by":{
      "user_id":"k7tm-2kym",
      "email":"test.user@socrata.com",
      "display_name":"Test User"
    }
  },
  "links":{
    "transform":"/api/publishing/v1/upload/8325/schema/9649",
    "show":"/api/publishing/v1/upload/8325/schema/9649",
    "latest_output":"/api/publishing/v1/upload/8325/schema/9649/output/latest"
  }
};

export const uploadShow = {
  "resource":{
    "schemas":[
      {
        "total_rows":null,
        "output_schemas":[
          {
            "output_columns":[
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332177
                    }
                  ],
                  "transform_expr":"to_number(`id`)",
                  "output_soql_type":"SoQLNumber",
                  "id":314244,
                  "completed_at":null
                },
                "position":0,
                "is_primary_key":false,
                "id":279376,
                "field_name":"id",
                "display_name":"ID",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332178
                    }
                  ],
                  "transform_expr":"`case_number`",
                  "output_soql_type":"SoQLText",
                  "id":314245,
                  "completed_at":null
                },
                "position":1,
                "is_primary_key":false,
                "id":279377,
                "field_name":"case_number",
                "display_name":"Case Number",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332179
                    }
                  ],
                  "transform_expr":"to_floating_timestamp(`date`)",
                  "output_soql_type":"SoQLFloatingTimestamp",
                  "id":314246,
                  "completed_at":null
                },
                "position":2,
                "is_primary_key":false,
                "id":279378,
                "field_name":"date",
                "display_name":"Date",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332180
                    }
                  ],
                  "transform_expr":"`block`",
                  "output_soql_type":"SoQLText",
                  "id":314247,
                  "completed_at":null
                },
                "position":3,
                "is_primary_key":false,
                "id":279379,
                "field_name":"block",
                "display_name":"Block",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332181
                    }
                  ],
                  "transform_expr":"`iucr`",
                  "output_soql_type":"SoQLText",
                  "id":314248,
                  "completed_at":null
                },
                "position":4,
                "is_primary_key":false,
                "id":279380,
                "field_name":"iucr",
                "display_name":"IUCR",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332182
                    }
                  ],
                  "transform_expr":"`primary_type`",
                  "output_soql_type":"SoQLText",
                  "id":314249,
                  "completed_at":null
                },
                "position":5,
                "is_primary_key":false,
                "id":279381,
                "field_name":"primary_type",
                "display_name":"Primary Type",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332183
                    }
                  ],
                  "transform_expr":"`description`",
                  "output_soql_type":"SoQLText",
                  "id":314250,
                  "completed_at":null
                },
                "position":6,
                "is_primary_key":false,
                "id":279382,
                "field_name":"description",
                "display_name":"Description",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332184
                    }
                  ],
                  "transform_expr":"`location_description`",
                  "output_soql_type":"SoQLText",
                  "id":314251,
                  "completed_at":null
                },
                "position":7,
                "is_primary_key":false,
                "id":279383,
                "field_name":"location_description",
                "display_name":"Location Description",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332185
                    }
                  ],
                  "transform_expr":"to_boolean(`arrest`)",
                  "output_soql_type":"SoQLBoolean",
                  "id":314252,
                  "completed_at":null
                },
                "position":8,
                "is_primary_key":false,
                "id":279384,
                "field_name":"arrest",
                "display_name":"Arrest",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332186
                    }
                  ],
                  "transform_expr":"to_boolean(`domestic`)",
                  "output_soql_type":"SoQLBoolean",
                  "id":314253,
                  "completed_at":null
                },
                "position":9,
                "is_primary_key":false,
                "id":279385,
                "field_name":"domestic",
                "display_name":"Domestic",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332187
                    }
                  ],
                  "transform_expr":"to_number(`beat`)",
                  "output_soql_type":"SoQLNumber",
                  "id":314254,
                  "completed_at":null
                },
                "position":10,
                "is_primary_key":false,
                "id":279386,
                "field_name":"beat",
                "display_name":"Beat",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332188
                    }
                  ],
                  "transform_expr":"to_number(`district`)",
                  "output_soql_type":"SoQLNumber",
                  "id":314255,
                  "completed_at":null
                },
                "position":11,
                "is_primary_key":false,
                "id":279387,
                "field_name":"district",
                "display_name":"District",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332189
                    }
                  ],
                  "transform_expr":"to_number(`ward`)",
                  "output_soql_type":"SoQLNumber",
                  "id":314256,
                  "completed_at":null
                },
                "position":12,
                "is_primary_key":false,
                "id":279388,
                "field_name":"ward",
                "display_name":"Ward",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332190
                    }
                  ],
                  "transform_expr":"to_number(`community_area`)",
                  "output_soql_type":"SoQLNumber",
                  "id":314257,
                  "completed_at":null
                },
                "position":13,
                "is_primary_key":false,
                "id":279389,
                "field_name":"community_area",
                "display_name":"Community Area",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332191
                    }
                  ],
                  "transform_expr":"`fbi_code`",
                  "output_soql_type":"SoQLText",
                  "id":314258,
                  "completed_at":null
                },
                "position":14,
                "is_primary_key":false,
                "id":279390,
                "field_name":"fbi_code",
                "display_name":"FBI Code",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332192
                    }
                  ],
                  "transform_expr":"to_number(`x_coordinate`)",
                  "output_soql_type":"SoQLNumber",
                  "id":314259,
                  "completed_at":null
                },
                "position":15,
                "is_primary_key":false,
                "id":279391,
                "field_name":"x_coordinate",
                "display_name":"X Coordinate",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332193
                    }
                  ],
                  "transform_expr":"to_number(`y_coordinate`)",
                  "output_soql_type":"SoQLNumber",
                  "id":314260,
                  "completed_at":null
                },
                "position":16,
                "is_primary_key":false,
                "id":279392,
                "field_name":"y_coordinate",
                "display_name":"Y Coordinate",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332194
                    }
                  ],
                  "transform_expr":"to_number(`year`)",
                  "output_soql_type":"SoQLNumber",
                  "id":314261,
                  "completed_at":null
                },
                "position":17,
                "is_primary_key":false,
                "id":279393,
                "field_name":"year",
                "display_name":"Year",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332195
                    }
                  ],
                  "transform_expr":"to_floating_timestamp(`updated_on`)",
                  "output_soql_type":"SoQLFloatingTimestamp",
                  "id":314262,
                  "completed_at":null
                },
                "position":18,
                "is_primary_key":false,
                "id":279394,
                "field_name":"updated_on",
                "display_name":"Updated On",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332196
                    }
                  ],
                  "transform_expr":"to_number(`latitude`)",
                  "output_soql_type":"SoQLNumber",
                  "id":314263,
                  "completed_at":null
                },
                "position":19,
                "is_primary_key":false,
                "id":279395,
                "field_name":"latitude",
                "display_name":"Latitude",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332197
                    }
                  ],
                  "transform_expr":"to_number(`longitude`)",
                  "output_soql_type":"SoQLNumber",
                  "id":314264,
                  "completed_at":null
                },
                "position":20,
                "is_primary_key":false,
                "id":279396,
                "field_name":"longitude",
                "display_name":"Longitude",
                "description":""
              },
              {
                "transform":{
                  "transform_input_columns":[
                    {
                      "input_column_id":332198
                    }
                  ],
                  "transform_expr":"`location`",
                  "output_soql_type":"SoQLText",
                  "id":314265,
                  "completed_at":null
                },
                "position":21,
                "is_primary_key":false,
                "id":279397,
                "field_name":"location",
                "display_name":"Location",
                "description":""
              }
            ],
            "inserted_at":"2017-05-11T18:31:49.251822",
            "input_schema_id":10378,
            "id":11197,
            "error_count":0,
            "created_by":{
              "user_id":"k7tm-2kym",
              "email":"brandon.webster@socrata.com",
              "display_name":"Brandon Webster"
            },
            "completed_at":null
          }
        ],
        "name":null,
        "inserted_at":"2017-05-11T18:31:46.708687",
        "input_columns":[
          {
            "soql_type":"SoQLText",
            "position":0,
            "input_schema_id":10378,
            "id":332177,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLNumber",
            "field_name":"id"
          },
          {
            "soql_type":"SoQLText",
            "position":1,
            "input_schema_id":10378,
            "id":332178,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLText",
            "field_name":"case_number"
          },
          {
            "soql_type":"SoQLText",
            "position":2,
            "input_schema_id":10378,
            "id":332179,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLFloatingTimestamp",
            "field_name":"date"
          },
          {
            "soql_type":"SoQLText",
            "position":3,
            "input_schema_id":10378,
            "id":332180,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLText",
            "field_name":"block"
          },
          {
            "soql_type":"SoQLText",
            "position":4,
            "input_schema_id":10378,
            "id":332181,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLText",
            "field_name":"iucr"
          },
          {
            "soql_type":"SoQLText",
            "position":5,
            "input_schema_id":10378,
            "id":332182,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLText",
            "field_name":"primary_type"
          },
          {
            "soql_type":"SoQLText",
            "position":6,
            "input_schema_id":10378,
            "id":332183,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLText",
            "field_name":"description"
          },
          {
            "soql_type":"SoQLText",
            "position":7,
            "input_schema_id":10378,
            "id":332184,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLText",
            "field_name":"location_description"
          },
          {
            "soql_type":"SoQLText",
            "position":8,
            "input_schema_id":10378,
            "id":332185,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLBoolean",
            "field_name":"arrest"
          },
          {
            "soql_type":"SoQLText",
            "position":9,
            "input_schema_id":10378,
            "id":332186,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLBoolean",
            "field_name":"domestic"
          },
          {
            "soql_type":"SoQLText",
            "position":10,
            "input_schema_id":10378,
            "id":332187,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLNumber",
            "field_name":"beat"
          },
          {
            "soql_type":"SoQLText",
            "position":11,
            "input_schema_id":10378,
            "id":332188,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLNumber",
            "field_name":"district"
          },
          {
            "soql_type":"SoQLText",
            "position":12,
            "input_schema_id":10378,
            "id":332189,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLNumber",
            "field_name":"ward"
          },
          {
            "soql_type":"SoQLText",
            "position":13,
            "input_schema_id":10378,
            "id":332190,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLNumber",
            "field_name":"community_area"
          },
          {
            "soql_type":"SoQLText",
            "position":14,
            "input_schema_id":10378,
            "id":332191,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLText",
            "field_name":"fbi_code"
          },
          {
            "soql_type":"SoQLText",
            "position":15,
            "input_schema_id":10378,
            "id":332192,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLNumber",
            "field_name":"x_coordinate"
          },
          {
            "soql_type":"SoQLText",
            "position":16,
            "input_schema_id":10378,
            "id":332193,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLNumber",
            "field_name":"y_coordinate"
          },
          {
            "soql_type":"SoQLText",
            "position":17,
            "input_schema_id":10378,
            "id":332194,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLNumber",
            "field_name":"year"
          },
          {
            "soql_type":"SoQLText",
            "position":18,
            "input_schema_id":10378,
            "id":332195,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLFloatingTimestamp",
            "field_name":"updated_on"
          },
          {
            "soql_type":"SoQLText",
            "position":19,
            "input_schema_id":10378,
            "id":332196,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLNumber",
            "field_name":"latitude"
          },
          {
            "soql_type":"SoQLText",
            "position":20,
            "input_schema_id":10378,
            "id":332197,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLNumber",
            "field_name":"longitude"
          },
          {
            "soql_type":"SoQLText",
            "position":21,
            "input_schema_id":10378,
            "id":332198,
            "guessed_subtypes":[

            ],
            "guessed_soql_type":"SoQLText",
            "field_name":"location"
          }
        ],
        "id":10378,
        "created_by":{
          "user_id":"k7tm-2kym",
          "email":"test.user@socrata.com",
          "display_name":"Test User"
        }
      }
    ],
    "inserted_at":"2017-05-09T23:10:16.339627",
    "id":8325,
    "finished_at":null,
    "filename":"petty_crimes.csv",
    "failed_at":null,
    "created_by":{
      "user_id":"k7tm-2kym",
      "email":"test.user@socrata.com",
      "display_name":"Test User"
    },
    "content_type":null
  },
  "links":{
    "show":"/api/publishing/v1/upload/8325",
    "bytes":"/api/publishing/v1/upload/8325",
    "add_to_revision":"/api/publishing/v1/upload/8325"
  }
};

export const newOutputSchema = {
  "resource":{
    "output_columns":[
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310263
            }
          ],
          "transform_expr":"to_text(id)",
          "output_soql_type":"SoQLText",
          "id":309525,
          "completed_at":null
        },
        "position":0,
        "is_primary_key":false,
        "id":274645,
        "field_name":"id",
        "display_name":"ID",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310264
            }
          ],
          "transform_expr":"`case_number`",
          "output_soql_type":"SoQLText",
          "id":285871,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":1,
        "is_primary_key":false,
        "id":250670,
        "field_name":"case_number",
        "display_name":"Case Number",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310265
            }
          ],
          "transform_expr":"to_floating_timestamp(`date`)",
          "output_soql_type":"SoQLFloatingTimestamp",
          "id":285872,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":2,
        "is_primary_key":false,
        "id":250671,
        "field_name":"date",
        "display_name":"Date",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310266
            }
          ],
          "transform_expr":"`block`",
          "output_soql_type":"SoQLText",
          "id":285873,
          "completed_at":"2017-05-09T23:10:20"
        },
        "position":3,
        "is_primary_key":false,
        "id":250672,
        "field_name":"block",
        "display_name":"Block",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310267
            }
          ],
          "transform_expr":"`iucr`",
          "output_soql_type":"SoQLText",
          "id":285874,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":4,
        "is_primary_key":false,
        "id":250673,
        "field_name":"iucr",
        "display_name":"IUCR",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310268
            }
          ],
          "transform_expr":"`primary_type`",
          "output_soql_type":"SoQLText",
          "id":285875,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":5,
        "is_primary_key":false,
        "id":250674,
        "field_name":"primary_type",
        "display_name":"Primary Type",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310269
            }
          ],
          "transform_expr":"`description`",
          "output_soql_type":"SoQLText",
          "id":285876,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":6,
        "is_primary_key":false,
        "id":250675,
        "field_name":"description",
        "display_name":"Description",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310270
            }
          ],
          "transform_expr":"`location_description`",
          "output_soql_type":"SoQLText",
          "id":285877,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":7,
        "is_primary_key":false,
        "id":250676,
        "field_name":"location_description",
        "display_name":"Location Description",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310271
            }
          ],
          "transform_expr":"to_boolean(`arrest`)",
          "output_soql_type":"SoQLBoolean",
          "id":285878,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":8,
        "is_primary_key":false,
        "id":250677,
        "field_name":"arrest",
        "display_name":"Arrest",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310272
            }
          ],
          "transform_expr":"to_boolean(`domestic`)",
          "output_soql_type":"SoQLBoolean",
          "id":285879,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":9,
        "is_primary_key":false,
        "id":250678,
        "field_name":"domestic",
        "display_name":"Domestic",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310273
            }
          ],
          "transform_expr":"to_number(`beat`)",
          "output_soql_type":"SoQLNumber",
          "id":285880,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":10,
        "is_primary_key":false,
        "id":250679,
        "field_name":"beat",
        "display_name":"Beat",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310274
            }
          ],
          "transform_expr":"to_number(`district`)",
          "output_soql_type":"SoQLNumber",
          "id":285881,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":11,
        "is_primary_key":false,
        "id":250680,
        "field_name":"district",
        "display_name":"District",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310275
            }
          ],
          "transform_expr":"to_number(`ward`)",
          "output_soql_type":"SoQLNumber",
          "id":285882,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":12,
        "is_primary_key":false,
        "id":250681,
        "field_name":"ward",
        "display_name":"Ward",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310276
            }
          ],
          "transform_expr":"to_number(`community_area`)",
          "output_soql_type":"SoQLNumber",
          "id":285883,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":13,
        "is_primary_key":false,
        "id":250682,
        "field_name":"community_area",
        "display_name":"Community Area",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310277
            }
          ],
          "transform_expr":"`fbi_code`",
          "output_soql_type":"SoQLText",
          "id":285884,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":14,
        "is_primary_key":false,
        "id":250683,
        "field_name":"fbi_code",
        "display_name":"FBI Code",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310278
            }
          ],
          "transform_expr":"to_number(`x_coordinate`)",
          "output_soql_type":"SoQLNumber",
          "id":285885,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":15,
        "is_primary_key":false,
        "id":250684,
        "field_name":"x_coordinate",
        "display_name":"X Coordinate",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310279
            }
          ],
          "transform_expr":"to_number(`y_coordinate`)",
          "output_soql_type":"SoQLNumber",
          "id":285886,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":16,
        "is_primary_key":false,
        "id":250685,
        "field_name":"y_coordinate",
        "display_name":"Y Coordinate",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310280
            }
          ],
          "transform_expr":"to_number(`year`)",
          "output_soql_type":"SoQLNumber",
          "id":285887,
          "completed_at":"2017-05-09T23:10:22"
        },
        "position":17,
        "is_primary_key":false,
        "id":250686,
        "field_name":"year",
        "display_name":"Year",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310281
            }
          ],
          "transform_expr":"to_floating_timestamp(`updated_on`)",
          "output_soql_type":"SoQLFloatingTimestamp",
          "id":285888,
          "completed_at":"2017-05-09T23:10:22"
        },
        "position":18,
        "is_primary_key":false,
        "id":250687,
        "field_name":"updated_on",
        "display_name":"Updated On",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310282
            }
          ],
          "transform_expr":"to_number(`latitude`)",
          "output_soql_type":"SoQLNumber",
          "id":285889,
          "completed_at":"2017-05-09T23:10:22"
        },
        "position":19,
        "is_primary_key":false,
        "id":250688,
        "field_name":"latitude",
        "display_name":"Latitude",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310283
            }
          ],
          "transform_expr":"to_number(`longitude`)",
          "output_soql_type":"SoQLNumber",
          "id":285890,
          "completed_at":"2017-05-09T23:10:22"
        },
        "position":20,
        "is_primary_key":false,
        "id":250689,
        "field_name":"longitude",
        "display_name":"Longitude",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310284
            }
          ],
          "transform_expr":"`location`",
          "output_soql_type":"SoQLText",
          "id":285891,
          "completed_at":"2017-05-09T23:10:22"
        },
        "position":21,
        "is_primary_key":false,
        "id":250690,
        "field_name":"location",
        "display_name":"Location",
        "description":""
      }
    ],
    "inserted_at":"2017-05-10T20:55:36.471437",
    "input_schema_id":9649,
    "id":10947,
    "error_count":0,
    "created_by":{
      "user_id":"k7tm-2kym",
      "email":"test.user@socrata.com",
      "display_name":"test user"
    },
    "completed_at":null
  },
  "links":{
    "show":"/api/publishing/v1/upload/8325/schema/9649/output/10947",
    "rows":"/api/publishing/v1/upload/8325/schema/9649/rows/10947"
  }
};

export const rows = [
  {
    "output_columns":[
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310263
            }
          ],
          "transform_expr":"to_text(id)",
          "output_soql_type":"SoQLText",
          "id":309525,
          "completed_at":"2017-05-10T20:55:36"
        },
        "position":0,
        "is_primary_key":false,
        "id":274645,
        "field_name":"id",
        "display_name":"ID",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310264
            }
          ],
          "transform_expr":"`case_number`",
          "output_soql_type":"SoQLText",
          "id":285871,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":1,
        "is_primary_key":false,
        "id":250670,
        "field_name":"case_number",
        "display_name":"Case Number",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310265
            }
          ],
          "transform_expr":"to_floating_timestamp(`date`)",
          "output_soql_type":"SoQLFloatingTimestamp",
          "id":285872,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":2,
        "is_primary_key":false,
        "id":250671,
        "field_name":"date",
        "display_name":"Date",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310266
            }
          ],
          "transform_expr":"`block`",
          "output_soql_type":"SoQLText",
          "id":285873,
          "completed_at":"2017-05-09T23:10:20"
        },
        "position":3,
        "is_primary_key":false,
        "id":250672,
        "field_name":"block",
        "display_name":"Block",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310267
            }
          ],
          "transform_expr":"`iucr`",
          "output_soql_type":"SoQLText",
          "id":285874,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":4,
        "is_primary_key":false,
        "id":250673,
        "field_name":"iucr",
        "display_name":"IUCR",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310268
            }
          ],
          "transform_expr":"`primary_type`",
          "output_soql_type":"SoQLText",
          "id":285875,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":5,
        "is_primary_key":false,
        "id":250674,
        "field_name":"primary_type",
        "display_name":"Primary Type",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310269
            }
          ],
          "transform_expr":"`description`",
          "output_soql_type":"SoQLText",
          "id":285876,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":6,
        "is_primary_key":false,
        "id":250675,
        "field_name":"description",
        "display_name":"Description",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310270
            }
          ],
          "transform_expr":"`location_description`",
          "output_soql_type":"SoQLText",
          "id":285877,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":7,
        "is_primary_key":false,
        "id":250676,
        "field_name":"location_description",
        "display_name":"Location Description",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310271
            }
          ],
          "transform_expr":"to_boolean(`arrest`)",
          "output_soql_type":"SoQLBoolean",
          "id":285878,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":8,
        "is_primary_key":false,
        "id":250677,
        "field_name":"arrest",
        "display_name":"Arrest",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310272
            }
          ],
          "transform_expr":"to_boolean(`domestic`)",
          "output_soql_type":"SoQLBoolean",
          "id":285879,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":9,
        "is_primary_key":false,
        "id":250678,
        "field_name":"domestic",
        "display_name":"Domestic",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310273
            }
          ],
          "transform_expr":"to_number(`beat`)",
          "output_soql_type":"SoQLNumber",
          "id":285880,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":10,
        "is_primary_key":false,
        "id":250679,
        "field_name":"beat",
        "display_name":"Beat",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310274
            }
          ],
          "transform_expr":"to_number(`district`)",
          "output_soql_type":"SoQLNumber",
          "id":285881,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":11,
        "is_primary_key":false,
        "id":250680,
        "field_name":"district",
        "display_name":"District",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310275
            }
          ],
          "transform_expr":"to_number(`ward`)",
          "output_soql_type":"SoQLNumber",
          "id":285882,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":12,
        "is_primary_key":false,
        "id":250681,
        "field_name":"ward",
        "display_name":"Ward",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310276
            }
          ],
          "transform_expr":"to_number(`community_area`)",
          "output_soql_type":"SoQLNumber",
          "id":285883,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":13,
        "is_primary_key":false,
        "id":250682,
        "field_name":"community_area",
        "display_name":"Community Area",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310277
            }
          ],
          "transform_expr":"`fbi_code`",
          "output_soql_type":"SoQLText",
          "id":285884,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":14,
        "is_primary_key":false,
        "id":250683,
        "field_name":"fbi_code",
        "display_name":"FBI Code",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310278
            }
          ],
          "transform_expr":"to_number(`x_coordinate`)",
          "output_soql_type":"SoQLNumber",
          "id":285885,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":15,
        "is_primary_key":false,
        "id":250684,
        "field_name":"x_coordinate",
        "display_name":"X Coordinate",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310279
            }
          ],
          "transform_expr":"to_number(`y_coordinate`)",
          "output_soql_type":"SoQLNumber",
          "id":285886,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":16,
        "is_primary_key":false,
        "id":250685,
        "field_name":"y_coordinate",
        "display_name":"Y Coordinate",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310280
            }
          ],
          "transform_expr":"to_number(`year`)",
          "output_soql_type":"SoQLNumber",
          "id":285887,
          "completed_at":"2017-05-09T23:10:22"
        },
        "position":17,
        "is_primary_key":false,
        "id":250686,
        "field_name":"year",
        "display_name":"Year",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310281
            }
          ],
          "transform_expr":"to_floating_timestamp(`updated_on`)",
          "output_soql_type":"SoQLFloatingTimestamp",
          "id":285888,
          "completed_at":"2017-05-09T23:10:22"
        },
        "position":18,
        "is_primary_key":false,
        "id":250687,
        "field_name":"updated_on",
        "display_name":"Updated On",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310282
            }
          ],
          "transform_expr":"to_number(`latitude`)",
          "output_soql_type":"SoQLNumber",
          "id":285889,
          "completed_at":"2017-05-09T23:10:22"
        },
        "position":19,
        "is_primary_key":false,
        "id":250688,
        "field_name":"latitude",
        "display_name":"Latitude",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310283
            }
          ],
          "transform_expr":"to_number(`longitude`)",
          "output_soql_type":"SoQLNumber",
          "id":285890,
          "completed_at":"2017-05-09T23:10:22"
        },
        "position":20,
        "is_primary_key":false,
        "id":250689,
        "field_name":"longitude",
        "display_name":"Longitude",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310284
            }
          ],
          "transform_expr":"`location`",
          "output_soql_type":"SoQLText",
          "id":285891,
          "completed_at":"2017-05-09T23:10:22"
        },
        "position":21,
        "is_primary_key":false,
        "id":250690,
        "field_name":"location",
        "display_name":"Location",
        "description":""
      }
    ],
    "inserted_at":"2017-05-10T20:55:36.471437",
    "input_schema_id":9649,
    "id":10947,
    "error_count":0,
    "created_by":{
      "user_id":"k7tm-2kym",
      "email":"test.user@socrata.com",
      "display_name":"Test User"
    },
    "completed_at":"2017-05-10T20:55:37"
  },
  {
    "row":[
      {
        "ok":"10376594"
      },
      {
        "ok":"HZ112917"
      },
      {
        "ok":"2016-01-11T23:53:00.000"
      },
      {
        "ok":"004XX S LARAMIE AVE"
      },
      {
        "ok":"031A"
      },
      {
        "ok":"ROBBERY"
      },
      {
        "ok":"ARMED: HANDGUN"
      },
      {
        "ok":"SIDEWALK"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"1522"
      },
      {
        "ok":"15"
      },
      {
        "ok":"29"
      },
      {
        "ok":"25"
      },
      {
        "ok":"3"
      },
      {
        "ok":"1141799"
      },
      {
        "ok":"1897396"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.87452002"
      },
      {
        "ok":"-87.75484623"
      },
      {
        "ok":"(41.874520022, -87.754846231)"
      }
    ],
    "offset":0
  },
  {
    "row":[
      {
        "ok":"10376574"
      },
      {
        "ok":"HZ112920"
      },
      {
        "ok":"2016-01-11T23:45:00.000"
      },
      {
        "ok":"003XX N CENTRAL AVE"
      },
      {
        "ok":"031A"
      },
      {
        "ok":"ROBBERY"
      },
      {
        "ok":"ARMED: HANDGUN"
      },
      {
        "ok":"STREET"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"1523"
      },
      {
        "ok":"15"
      },
      {
        "ok":"28"
      },
      {
        "ok":"25"
      },
      {
        "ok":"3"
      },
      {
        "ok":"1138978"
      },
      {
        "ok":"1901836"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.88675567"
      },
      {
        "ok":"-87.76509592"
      },
      {
        "ok":"(41.886755667, -87.765095923)"
      }
    ],
    "offset":1
  },
  {
    "row":[
      {
        "ok":"10376371"
      },
      {
        "ok":"HZ112605"
      },
      {
        "ok":"2016-01-11T23:30:00.000"
      },
      {
        "ok":"004XX E 48TH ST"
      },
      {
        "ok":"910"
      },
      {
        "ok":"MOTOR VEHICLE THEFT"
      },
      {
        "ok":"AUTOMOBILE"
      },
      {
        "ok":"STREET"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"223"
      },
      {
        "ok":"2"
      },
      {
        "ok":"3"
      },
      {
        "ok":"38"
      },
      {
        "ok":"7"
      },
      {
        "ok":"1180055"
      },
      {
        "ok":"1873293"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.80758633"
      },
      {
        "ok":"-87.61512779"
      },
      {
        "ok":"(41.807586328, -87.615127788)"
      }
    ],
    "offset":2
  },
  {
    "row":[
      {
        "ok":"10380234"
      },
      {
        "ok":"HZ116304"
      },
      {
        "ok":"2016-01-11T23:30:00.000"
      },
      {
        "ok":"055XX S CORNELL AVE"
      },
      {
        "ok":"910"
      },
      {
        "ok":"MOTOR VEHICLE THEFT"
      },
      {
        "ok":"AUTOMOBILE"
      },
      {
        "ok":"STREET"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"235"
      },
      {
        "ok":"2"
      },
      {
        "ok":"5"
      },
      {
        "ok":"41"
      },
      {
        "ok":"7"
      },
      {
        "ok":"1188201"
      },
      {
        "ok":"1868688"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.7947592"
      },
      {
        "ok":"-87.58539793"
      },
      {
        "ok":"(41.794759204, -87.585397931)"
      }
    ],
    "offset":3
  },
  {
    "row":[
      {
        "ok":"10375856"
      },
      {
        "ok":"HZ112435"
      },
      {
        "ok":"2016-01-11T23:30:00.000"
      },
      {
        "ok":"001XX S CENTRAL AVE"
      },
      {
        "ok":"560"
      },
      {
        "ok":"ASSAULT"
      },
      {
        "ok":"SIMPLE"
      },
      {
        "ok":"RESIDENCE"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"1522"
      },
      {
        "ok":"15"
      },
      {
        "ok":"29"
      },
      {
        "ok":"25"
      },
      {
        "ok":"08A"
      },
      {
        "ok":"1139082"
      },
      {
        "ok":"1898717"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.87819484"
      },
      {
        "ok":"-87.76478988"
      },
      {
        "ok":"(41.878194837, -87.764789883)"
      }
    ],
    "offset":4
  },
  {
    "row":[
      {
        "ok":"10375836"
      },
      {
        "ok":"HZ112407"
      },
      {
        "ok":"2016-01-11T23:25:00.000"
      },
      {
        "ok":"063XX S KEDZIE AVE"
      },
      {
        "ok":"1330"
      },
      {
        "ok":"CRIMINAL TRESPASS"
      },
      {
        "ok":"TO LAND"
      },
      {
        "ok":"DRUG STORE"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"823"
      },
      {
        "ok":"8"
      },
      {
        "ok":"15"
      },
      {
        "ok":"66"
      },
      {
        "ok":"26"
      },
      {
        "ok":"1156143"
      },
      {
        "ok":"1862448"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.77834098"
      },
      {
        "ok":"-87.70312224"
      },
      {
        "ok":"(41.778340981, -87.703122242)"
      }
    ],
    "offset":5
  },
  {
    "row":[
      {
        "ok":"10376791"
      },
      {
        "ok":"HZ112953"
      },
      {
        "ok":"2016-01-11T23:20:00.000"
      },
      {
        "ok":"004XX W 76TH ST"
      },
      {
        "ok":"031A"
      },
      {
        "ok":"ROBBERY"
      },
      {
        "ok":"ARMED: HANDGUN"
      },
      {
        "ok":"OTHER"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"621"
      },
      {
        "ok":"6"
      },
      {
        "ok":"17"
      },
      {
        "ok":"69"
      },
      {
        "ok":"3"
      },
      {
        "ok":"1174859"
      },
      {
        "ok":"1854542"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.75624913"
      },
      {
        "ok":"-87.63474388"
      },
      {
        "ok":"(41.756249125, -87.634743877)"
      }
    ],
    "offset":6
  },
  {
    "row":[
      {
        "ok":"10375849"
      },
      {
        "ok":"HZ112411"
      },
      {
        "ok":"2016-01-11T23:15:00.000"
      },
      {
        "ok":"024XX N NARRAGANSETT AVE"
      },
      {
        "ok":"460"
      },
      {
        "ok":"BATTERY"
      },
      {
        "ok":"SIMPLE"
      },
      {
        "ok":"ATHLETIC CLUB"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"2512"
      },
      {
        "ok":"25"
      },
      {
        "ok":"36"
      },
      {
        "ok":"19"
      },
      {
        "ok":"08B"
      },
      {
        "ok":"1133346"
      },
      {
        "ok":"1915440"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.92418726"
      },
      {
        "ok":"-87.7854594"
      },
      {
        "ok":"(41.924187262, -87.785459395)"
      }
    ],
    "offset":7
  },
  {
    "row":[
      {
        "ok":"10376251"
      },
      {
        "ok":"HZ112670"
      },
      {
        "ok":"2016-01-11T23:15:00.000"
      },
      {
        "ok":"037XX W FLOURNOY ST"
      },
      {
        "ok":"820"
      },
      {
        "ok":"THEFT"
      },
      {
        "ok":"$500 AND UNDER"
      },
      {
        "ok":"STREET"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"1133"
      },
      {
        "ok":"11"
      },
      {
        "ok":"24"
      },
      {
        "ok":"27"
      },
      {
        "ok":"6"
      },
      {
        "ok":"1151652"
      },
      {
        "ok":"1896775"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.87262801"
      },
      {
        "ok":"-87.71868635"
      },
      {
        "ok":"(41.872628006, -87.718686345)"
      }
    ],
    "offset":8
  }
]

export const columnErrors = [
  {
    "output_columns":[
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310263
            }
          ],
          "transform_expr":"to_number(id)",
          "output_soql_type":"SoQLNumber",
          "id":310324,
          "completed_at":"2017-05-10T21:43:53"
        },
        "position":0,
        "is_primary_key":false,
        "id":275448,
        "field_name":"id",
        "display_name":"ID",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310264
            }
          ],
          "transform_expr":"to_boolean(case_number)",
          "output_soql_type":"SoQLBoolean",
          "id":310325,
          "completed_at":"2017-05-10T23:29:33"
        },
        "position":1,
        "is_primary_key":false,
        "id":275449,
        "field_name":"case_number",
        "display_name":"Case Number",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310265
            }
          ],
          "transform_expr":"to_floating_timestamp(`date`)",
          "output_soql_type":"SoQLFloatingTimestamp",
          "id":285872,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":2,
        "is_primary_key":false,
        "id":250671,
        "field_name":"date",
        "display_name":"Date",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310266
            }
          ],
          "transform_expr":"`block`",
          "output_soql_type":"SoQLText",
          "id":285873,
          "completed_at":"2017-05-09T23:10:20"
        },
        "position":3,
        "is_primary_key":false,
        "id":250672,
        "field_name":"block",
        "display_name":"Block",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310267
            }
          ],
          "transform_expr":"`iucr`",
          "output_soql_type":"SoQLText",
          "id":285874,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":4,
        "is_primary_key":false,
        "id":250673,
        "field_name":"iucr",
        "display_name":"IUCR",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310268
            }
          ],
          "transform_expr":"`primary_type`",
          "output_soql_type":"SoQLText",
          "id":285875,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":5,
        "is_primary_key":false,
        "id":250674,
        "field_name":"primary_type",
        "display_name":"Primary Type",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310269
            }
          ],
          "transform_expr":"`description`",
          "output_soql_type":"SoQLText",
          "id":285876,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":6,
        "is_primary_key":false,
        "id":250675,
        "field_name":"description",
        "display_name":"Description",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310270
            }
          ],
          "transform_expr":"`location_description`",
          "output_soql_type":"SoQLText",
          "id":285877,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":7,
        "is_primary_key":false,
        "id":250676,
        "field_name":"location_description",
        "display_name":"Location Description",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310271
            }
          ],
          "transform_expr":"to_boolean(`arrest`)",
          "output_soql_type":"SoQLBoolean",
          "id":285878,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":8,
        "is_primary_key":false,
        "id":250677,
        "field_name":"arrest",
        "display_name":"Arrest",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310272
            }
          ],
          "transform_expr":"to_boolean(`domestic`)",
          "output_soql_type":"SoQLBoolean",
          "id":285879,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":9,
        "is_primary_key":false,
        "id":250678,
        "field_name":"domestic",
        "display_name":"Domestic",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310273
            }
          ],
          "transform_expr":"to_number(`beat`)",
          "output_soql_type":"SoQLNumber",
          "id":285880,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":10,
        "is_primary_key":false,
        "id":250679,
        "field_name":"beat",
        "display_name":"Beat",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310274
            }
          ],
          "transform_expr":"to_number(`district`)",
          "output_soql_type":"SoQLNumber",
          "id":285881,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":11,
        "is_primary_key":false,
        "id":250680,
        "field_name":"district",
        "display_name":"District",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310275
            }
          ],
          "transform_expr":"to_number(`ward`)",
          "output_soql_type":"SoQLNumber",
          "id":285882,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":12,
        "is_primary_key":false,
        "id":250681,
        "field_name":"ward",
        "display_name":"Ward",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310276
            }
          ],
          "transform_expr":"to_number(`community_area`)",
          "output_soql_type":"SoQLNumber",
          "id":285883,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":13,
        "is_primary_key":false,
        "id":250682,
        "field_name":"community_area",
        "display_name":"Community Area",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310277
            }
          ],
          "transform_expr":"`fbi_code`",
          "output_soql_type":"SoQLText",
          "id":285884,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":14,
        "is_primary_key":false,
        "id":250683,
        "field_name":"fbi_code",
        "display_name":"FBI Code",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310278
            }
          ],
          "transform_expr":"to_number(`x_coordinate`)",
          "output_soql_type":"SoQLNumber",
          "id":285885,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":15,
        "is_primary_key":false,
        "id":250684,
        "field_name":"x_coordinate",
        "display_name":"X Coordinate",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310279
            }
          ],
          "transform_expr":"to_number(`y_coordinate`)",
          "output_soql_type":"SoQLNumber",
          "id":285886,
          "completed_at":"2017-05-09T23:10:21"
        },
        "position":16,
        "is_primary_key":false,
        "id":250685,
        "field_name":"y_coordinate",
        "display_name":"Y Coordinate",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310280
            }
          ],
          "transform_expr":"to_number(`year`)",
          "output_soql_type":"SoQLNumber",
          "id":285887,
          "completed_at":"2017-05-09T23:10:22"
        },
        "position":17,
        "is_primary_key":false,
        "id":250686,
        "field_name":"year",
        "display_name":"Year",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310281
            }
          ],
          "transform_expr":"to_floating_timestamp(`updated_on`)",
          "output_soql_type":"SoQLFloatingTimestamp",
          "id":285888,
          "completed_at":"2017-05-09T23:10:22"
        },
        "position":18,
        "is_primary_key":false,
        "id":250687,
        "field_name":"updated_on",
        "display_name":"Updated On",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310282
            }
          ],
          "transform_expr":"to_number(`latitude`)",
          "output_soql_type":"SoQLNumber",
          "id":285889,
          "completed_at":"2017-05-09T23:10:22"
        },
        "position":19,
        "is_primary_key":false,
        "id":250688,
        "field_name":"latitude",
        "display_name":"Latitude",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310283
            }
          ],
          "transform_expr":"to_number(`longitude`)",
          "output_soql_type":"SoQLNumber",
          "id":285890,
          "completed_at":"2017-05-09T23:10:22"
        },
        "position":20,
        "is_primary_key":false,
        "id":250689,
        "field_name":"longitude",
        "display_name":"Longitude",
        "description":""
      },
      {
        "transform":{
          "transform_input_columns":[
            {
              "input_column_id":310284
            }
          ],
          "transform_expr":"`location`",
          "output_soql_type":"SoQLText",
          "id":285891,
          "completed_at":"2017-05-09T23:10:22"
        },
        "position":21,
        "is_primary_key":false,
        "id":250690,
        "field_name":"location",
        "display_name":"Location",
        "description":""
      }
    ],
    "inserted_at":"2017-05-10T21:44:03.897815",
    "input_schema_id":9649,
    "id":10974,
    "error_count":9,
    "created_by":{
      "user_id":"k7tm-2kym",
      "email":"brandon.webster@socrata.com",
      "display_name":"Brandon Webster"
    },
    "completed_at":"2017-05-10T23:29:33"
  },
  {
    "row":[
      {
        "ok":"10376594"
      },
      {
        "error":{
          "message":"Failed to convert \"HZ112917\" to boolean",
          "inputs":{
            "case_number":{
              "ok":"HZ112917"
            }
          }
        }
      },
      {
        "ok":"2016-01-11T23:53:00.000"
      },
      {
        "ok":"004XX S LARAMIE AVE"
      },
      {
        "ok":"031A"
      },
      {
        "ok":"ROBBERY"
      },
      {
        "ok":"ARMED: HANDGUN"
      },
      {
        "ok":"SIDEWALK"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"1522"
      },
      {
        "ok":"15"
      },
      {
        "ok":"29"
      },
      {
        "ok":"25"
      },
      {
        "ok":"3"
      },
      {
        "ok":"1141799"
      },
      {
        "ok":"1897396"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.87452002"
      },
      {
        "ok":"-87.75484623"
      },
      {
        "ok":"(41.874520022, -87.754846231)"
      }
    ],
    "offset":0
  },
  {
    "row":[
      {
        "ok":"10376574"
      },
      {
        "error":{
          "message":"Failed to convert \"HZ112920\" to boolean",
          "inputs":{
            "case_number":{
              "ok":"HZ112920"
            }
          }
        }
      },
      {
        "ok":"2016-01-11T23:45:00.000"
      },
      {
        "ok":"003XX N CENTRAL AVE"
      },
      {
        "ok":"031A"
      },
      {
        "ok":"ROBBERY"
      },
      {
        "ok":"ARMED: HANDGUN"
      },
      {
        "ok":"STREET"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"1523"
      },
      {
        "ok":"15"
      },
      {
        "ok":"28"
      },
      {
        "ok":"25"
      },
      {
        "ok":"3"
      },
      {
        "ok":"1138978"
      },
      {
        "ok":"1901836"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.88675567"
      },
      {
        "ok":"-87.76509592"
      },
      {
        "ok":"(41.886755667, -87.765095923)"
      }
    ],
    "offset":1
  },
  {
    "row":[
      {
        "ok":"10376371"
      },
      {
        "error":{
          "message":"Failed to convert \"HZ112605\" to boolean",
          "inputs":{
            "case_number":{
              "ok":"HZ112605"
            }
          }
        }
      },
      {
        "ok":"2016-01-11T23:30:00.000"
      },
      {
        "ok":"004XX E 48TH ST"
      },
      {
        "ok":"910"
      },
      {
        "ok":"MOTOR VEHICLE THEFT"
      },
      {
        "ok":"AUTOMOBILE"
      },
      {
        "ok":"STREET"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"223"
      },
      {
        "ok":"2"
      },
      {
        "ok":"3"
      },
      {
        "ok":"38"
      },
      {
        "ok":"7"
      },
      {
        "ok":"1180055"
      },
      {
        "ok":"1873293"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.80758633"
      },
      {
        "ok":"-87.61512779"
      },
      {
        "ok":"(41.807586328, -87.615127788)"
      }
    ],
    "offset":2
  },
  {
    "row":[
      {
        "ok":"10380234"
      },
      {
        "error":{
          "message":"Failed to convert \"HZ116304\" to boolean",
          "inputs":{
            "case_number":{
              "ok":"HZ116304"
            }
          }
        }
      },
      {
        "ok":"2016-01-11T23:30:00.000"
      },
      {
        "ok":"055XX S CORNELL AVE"
      },
      {
        "ok":"910"
      },
      {
        "ok":"MOTOR VEHICLE THEFT"
      },
      {
        "ok":"AUTOMOBILE"
      },
      {
        "ok":"STREET"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"235"
      },
      {
        "ok":"2"
      },
      {
        "ok":"5"
      },
      {
        "ok":"41"
      },
      {
        "ok":"7"
      },
      {
        "ok":"1188201"
      },
      {
        "ok":"1868688"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.7947592"
      },
      {
        "ok":"-87.58539793"
      },
      {
        "ok":"(41.794759204, -87.585397931)"
      }
    ],
    "offset":3
  },
  {
    "row":[
      {
        "ok":"10375856"
      },
      {
        "error":{
          "message":"Failed to convert \"HZ112435\" to boolean",
          "inputs":{
            "case_number":{
              "ok":"HZ112435"
            }
          }
        }
      },
      {
        "ok":"2016-01-11T23:30:00.000"
      },
      {
        "ok":"001XX S CENTRAL AVE"
      },
      {
        "ok":"560"
      },
      {
        "ok":"ASSAULT"
      },
      {
        "ok":"SIMPLE"
      },
      {
        "ok":"RESIDENCE"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"1522"
      },
      {
        "ok":"15"
      },
      {
        "ok":"29"
      },
      {
        "ok":"25"
      },
      {
        "ok":"08A"
      },
      {
        "ok":"1139082"
      },
      {
        "ok":"1898717"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.87819484"
      },
      {
        "ok":"-87.76478988"
      },
      {
        "ok":"(41.878194837, -87.764789883)"
      }
    ],
    "offset":4
  },
  {
    "row":[
      {
        "ok":"10375836"
      },
      {
        "error":{
          "message":"Failed to convert \"HZ112407\" to boolean",
          "inputs":{
            "case_number":{
              "ok":"HZ112407"
            }
          }
        }
      },
      {
        "ok":"2016-01-11T23:25:00.000"
      },
      {
        "ok":"063XX S KEDZIE AVE"
      },
      {
        "ok":"1330"
      },
      {
        "ok":"CRIMINAL TRESPASS"
      },
      {
        "ok":"TO LAND"
      },
      {
        "ok":"DRUG STORE"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"823"
      },
      {
        "ok":"8"
      },
      {
        "ok":"15"
      },
      {
        "ok":"66"
      },
      {
        "ok":"26"
      },
      {
        "ok":"1156143"
      },
      {
        "ok":"1862448"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.77834098"
      },
      {
        "ok":"-87.70312224"
      },
      {
        "ok":"(41.778340981, -87.703122242)"
      }
    ],
    "offset":5
  },
  {
    "row":[
      {
        "ok":"10376791"
      },
      {
        "error":{
          "message":"Failed to convert \"HZ112953\" to boolean",
          "inputs":{
            "case_number":{
              "ok":"HZ112953"
            }
          }
        }
      },
      {
        "ok":"2016-01-11T23:20:00.000"
      },
      {
        "ok":"004XX W 76TH ST"
      },
      {
        "ok":"031A"
      },
      {
        "ok":"ROBBERY"
      },
      {
        "ok":"ARMED: HANDGUN"
      },
      {
        "ok":"OTHER"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"621"
      },
      {
        "ok":"6"
      },
      {
        "ok":"17"
      },
      {
        "ok":"69"
      },
      {
        "ok":"3"
      },
      {
        "ok":"1174859"
      },
      {
        "ok":"1854542"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.75624913"
      },
      {
        "ok":"-87.63474388"
      },
      {
        "ok":"(41.756249125, -87.634743877)"
      }
    ],
    "offset":6
  },
  {
    "row":[
      {
        "ok":"10375849"
      },
      {
        "error":{
          "message":"Failed to convert \"HZ112411\" to boolean",
          "inputs":{
            "case_number":{
              "ok":"HZ112411"
            }
          }
        }
      },
      {
        "ok":"2016-01-11T23:15:00.000"
      },
      {
        "ok":"024XX N NARRAGANSETT AVE"
      },
      {
        "ok":"460"
      },
      {
        "ok":"BATTERY"
      },
      {
        "ok":"SIMPLE"
      },
      {
        "ok":"ATHLETIC CLUB"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"2512"
      },
      {
        "ok":"25"
      },
      {
        "ok":"36"
      },
      {
        "ok":"19"
      },
      {
        "ok":"08B"
      },
      {
        "ok":"1133346"
      },
      {
        "ok":"1915440"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.92418726"
      },
      {
        "ok":"-87.7854594"
      },
      {
        "ok":"(41.924187262, -87.785459395)"
      }
    ],
    "offset":7
  },
  {
    "row":[
      {
        "ok":"10376251"
      },
      {
        "error":{
          "message":"Failed to convert \"HZ112670\" to boolean",
          "inputs":{
            "case_number":{
              "ok":"HZ112670"
            }
          }
        }
      },
      {
        "ok":"2016-01-11T23:15:00.000"
      },
      {
        "ok":"037XX W FLOURNOY ST"
      },
      {
        "ok":"820"
      },
      {
        "ok":"THEFT"
      },
      {
        "ok":"$500 AND UNDER"
      },
      {
        "ok":"STREET"
      },
      {
        "ok":false
      },
      {
        "ok":false
      },
      {
        "ok":"1133"
      },
      {
        "ok":"11"
      },
      {
        "ok":"24"
      },
      {
        "ok":"27"
      },
      {
        "ok":"6"
      },
      {
        "ok":"1151652"
      },
      {
        "ok":"1896775"
      },
      {
        "ok":"2016"
      },
      {
        "ok":"2016-01-18T15:54:00.000"
      },
      {
        "ok":"41.87262801"
      },
      {
        "ok":"-87.71868635"
      },
      {
        "ok":"(41.872628006, -87.718686345)"
      }
    ],
    "offset":8
  }
]

export const errorExport = {
  "errors": "blah"
};

export const rowErrors = [
  {
    "offset":9,
    "error":{
      "wanted":22,
      "type":"too_short",
      "got":21,
      "contents":[
        null,
        null,
        null,
        null,
        "66",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    }
  },
  {
    "offset":10,
    "error":{
      "wanted":22,
      "type":"too_short",
      "got":21,
      "contents":[
        null,
        null,
        null,
        "44",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ]
    }
  }
];

export const validateRowIdentifier = {"valid":true};
