export const uploadCreate = {
  "resource":{
    "schemas":[],
    "inserted_at":"2017-05-09T23:10:16.339627",
    "id":8325,
    "finished_at":null,
    "filename":"petty_crimes.csv",
    "failed_at":null,
    "created_by":{
       "user_id":"k7tm-2kym",
       "email":"test.user@socrata.com",
       "display_name":"Test User"
    },
    "content_type":null
  },
  "links":{
    "show":"/api/publishing/v1/upload/8325",
    "bytes":"/api/publishing/v1/upload/8325",
    "add_to_revision":"/api/publishing/v1/upload/8325"
  }
};

export const uploadBytes = {
  "resource":{
    "total_rows":9,
    "output_schemas":[
      {
        "output_columns":[
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310263
                }
              ],
              "transform_expr":"to_number(`id`)",
              "output_soql_type":"SoQLNumber",
              "id":285870,
              "completed_at":"2017-05-09T23:10:21"
            },
            "position":0,
            "is_primary_key":false,
            "id":250669,
            "field_name":"id",
            "display_name":"ID",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310264
                }
              ],
              "transform_expr":"`case_number`",
              "output_soql_type":"SoQLText",
              "id":285871,
              "completed_at":"2017-05-09T23:10:21"
            },
            "position":1,
            "is_primary_key":false,
            "id":250670,
            "field_name":"case_number",
            "display_name":"Case Number",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310265
                }
              ],
              "transform_expr":"to_floating_timestamp(`date`)",
              "output_soql_type":"SoQLFloatingTimestamp",
              "id":285872,
              "completed_at":"2017-05-09T23:10:21"
            },
            "position":2,
            "is_primary_key":false,
            "id":250671,
            "field_name":"date",
            "display_name":"Date",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310266
                }
              ],
              "transform_expr":"`block`",
              "output_soql_type":"SoQLText",
              "id":285873,
              "completed_at":"2017-05-09T23:10:20"
            },
            "position":3,
            "is_primary_key":false,
            "id":250672,
            "field_name":"block",
            "display_name":"Block",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310267
                }
              ],
              "transform_expr":"`iucr`",
              "output_soql_type":"SoQLText",
              "id":285874,
              "completed_at":"2017-05-09T23:10:21"
            },
            "position":4,
            "is_primary_key":false,
            "id":250673,
            "field_name":"iucr",
            "display_name":"IUCR",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310268
                }
              ],
              "transform_expr":"`primary_type`",
              "output_soql_type":"SoQLText",
              "id":285875,
              "completed_at":"2017-05-09T23:10:21"
            },
            "position":5,
            "is_primary_key":false,
            "id":250674,
            "field_name":"primary_type",
            "display_name":"Primary Type",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310269
                }
              ],
              "transform_expr":"`description`",
              "output_soql_type":"SoQLText",
              "id":285876,
              "completed_at":null
            },
            "position":6,
            "is_primary_key":false,
            "id":250675,
            "field_name":"description",
            "display_name":"Description",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310270
                }
              ],
              "transform_expr":"`location_description`",
              "output_soql_type":"SoQLText",
              "id":285877,
              "completed_at":null
            },
            "position":7,
            "is_primary_key":false,
            "id":250676,
            "field_name":"location_description",
            "display_name":"Location Description",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310271
                }
              ],
              "transform_expr":"to_boolean(`arrest`)",
              "output_soql_type":"SoQLBoolean",
              "id":285878,
              "completed_at":null
            },
            "position":8,
            "is_primary_key":false,
            "id":250677,
            "field_name":"arrest",
            "display_name":"Arrest",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310272
                }
              ],
              "transform_expr":"to_boolean(`domestic`)",
              "output_soql_type":"SoQLBoolean",
              "id":285879,
              "completed_at":null
            },
            "position":9,
            "is_primary_key":false,
            "id":250678,
            "field_name":"domestic",
            "display_name":"Domestic",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310273
                }
              ],
              "transform_expr":"to_number(`beat`)",
              "output_soql_type":"SoQLNumber",
              "id":285880,
              "completed_at":null
            },
            "position":10,
            "is_primary_key":false,
            "id":250679,
            "field_name":"beat",
            "display_name":"Beat",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310274
                }
              ],
              "transform_expr":"to_number(`district`)",
              "output_soql_type":"SoQLNumber",
              "id":285881,
              "completed_at":null
            },
            "position":11,
            "is_primary_key":false,
            "id":250680,
            "field_name":"district",
            "display_name":"District",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310275
                }
              ],
              "transform_expr":"to_number(`ward`)",
              "output_soql_type":"SoQLNumber",
              "id":285882,
              "completed_at":null
            },
            "position":12,
            "is_primary_key":false,
            "id":250681,
            "field_name":"ward",
            "display_name":"Ward",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310276
                }
              ],
              "transform_expr":"to_number(`community_area`)",
              "output_soql_type":"SoQLNumber",
              "id":285883,
              "completed_at":null
            },
            "position":13,
            "is_primary_key":false,
            "id":250682,
            "field_name":"community_area",
            "display_name":"Community Area",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310277
                }
              ],
              "transform_expr":"`fbi_code`",
              "output_soql_type":"SoQLText",
              "id":285884,
              "completed_at":null
            },
            "position":14,
            "is_primary_key":false,
            "id":250683,
            "field_name":"fbi_code",
            "display_name":"FBI Code",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310278
                }
              ],
              "transform_expr":"to_number(`x_coordinate`)",
              "output_soql_type":"SoQLNumber",
              "id":285885,
              "completed_at":null
            },
            "position":15,
            "is_primary_key":false,
            "id":250684,
            "field_name":"x_coordinate",
            "display_name":"X Coordinate",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310279
                }
              ],
              "transform_expr":"to_number(`y_coordinate`)",
              "output_soql_type":"SoQLNumber",
              "id":285886,
              "completed_at":null
            },
            "position":16,
            "is_primary_key":false,
            "id":250685,
            "field_name":"y_coordinate",
            "display_name":"Y Coordinate",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310280
                }
              ],
              "transform_expr":"to_number(`year`)",
              "output_soql_type":"SoQLNumber",
              "id":285887,
              "completed_at":null
            },
            "position":17,
            "is_primary_key":false,
            "id":250686,
            "field_name":"year",
            "display_name":"Year",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310281
                }
              ],
              "transform_expr":"to_floating_timestamp(`updated_on`)",
              "output_soql_type":"SoQLFloatingTimestamp",
              "id":285888,
              "completed_at":null
            },
            "position":18,
            "is_primary_key":false,
            "id":250687,
            "field_name":"updated_on",
            "display_name":"Updated On",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310282
                }
              ],
              "transform_expr":"to_number(`latitude`)",
              "output_soql_type":"SoQLNumber",
              "id":285889,
              "completed_at":null
            },
            "position":19,
            "is_primary_key":false,
            "id":250688,
            "field_name":"latitude",
            "display_name":"Latitude",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310283
                }
              ],
              "transform_expr":"to_number(`longitude`)",
              "output_soql_type":"SoQLNumber",
              "id":285890,
              "completed_at":null
            },
            "position":20,
            "is_primary_key":false,
            "id":250689,
            "field_name":"longitude",
            "display_name":"Longitude",
            "description":""
          },
          {
            "transform":{
              "transform_input_columns":[
                {
                  "input_column_id":310284
                }
              ],
              "transform_expr":"`location`",
              "output_soql_type":"SoQLText",
              "id":285891,
              "completed_at":null
            },
            "position":21,
            "is_primary_key":false,
            "id":250690,
            "field_name":"location",
            "display_name":"Location",
            "description":""
          }
        ],
        "inserted_at":"2017-05-09T23:10:19.128086",
        "input_schema_id":9649,
        "id":9908,
        "error_count":0,
        "created_by":{
          "user_id":"k7tm-2kym",
          "email":"brandon.webster@socrata.com",
          "display_name":"Brandon Webster"
        },
        "completed_at":null
      }
    ],
    "name":null,
    "inserted_at":"2017-05-09T23:10:16.485161",
    "input_columns":[
      {
        "soql_type":"SoQLText",
        "position":0,
        "input_schema_id":9649,
        "id":310263,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"id"
      },
      {
        "soql_type":"SoQLText",
        "position":1,
        "input_schema_id":9649,
        "id":310264,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLText",
        "field_name":"case_number"
      },
      {
        "soql_type":"SoQLText",
        "position":2,
        "input_schema_id":9649,
        "id":310265,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLFloatingTimestamp",
        "field_name":"date"
      },
      {
        "soql_type":"SoQLText",
        "position":3,
        "input_schema_id":9649,
        "id":310266,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLText",
        "field_name":"block"
      },
      {
        "soql_type":"SoQLText",
        "position":4,
        "input_schema_id":9649,
        "id":310267,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLText",
        "field_name":"iucr"
      },
      {
        "soql_type":"SoQLText",
        "position":5,
        "input_schema_id":9649,
        "id":310268,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLText",
        "field_name":"primary_type"
      },
      {
        "soql_type":"SoQLText",
        "position":6,
        "input_schema_id":9649,
        "id":310269,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLText",
        "field_name":"description"
      },
      {
        "soql_type":"SoQLText",
        "position":7,
        "input_schema_id":9649,
        "id":310270,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLText",
        "field_name":"location_description"
      },
      {
        "soql_type":"SoQLText",
        "position":8,
        "input_schema_id":9649,
        "id":310271,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLBoolean",
        "field_name":"arrest"
      },
      {
        "soql_type":"SoQLText",
        "position":9,
        "input_schema_id":9649,
        "id":310272,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLBoolean",
        "field_name":"domestic"
      },
      {
        "soql_type":"SoQLText",
        "position":10,
        "input_schema_id":9649,
        "id":310273,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"beat"
      },
      {
        "soql_type":"SoQLText",
        "position":11,
        "input_schema_id":9649,
        "id":310274,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"district"
      },
      {
        "soql_type":"SoQLText",
        "position":12,
        "input_schema_id":9649,
        "id":310275,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"ward"
      },
      {
        "soql_type":"SoQLText",
        "position":13,
        "input_schema_id":9649,
        "id":310276,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"community_area"
      },
      {
        "soql_type":"SoQLText",
        "position":14,
        "input_schema_id":9649,
        "id":310277,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLText",
        "field_name":"fbi_code"
      },
      {
        "soql_type":"SoQLText",
        "position":15,
        "input_schema_id":9649,
        "id":310278,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"x_coordinate"
      },
      {
        "soql_type":"SoQLText",
        "position":16,
        "input_schema_id":9649,
        "id":310279,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"y_coordinate"
      },
      {
        "soql_type":"SoQLText",
        "position":17,
        "input_schema_id":9649,
        "id":310280,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"year"
      },
      {
        "soql_type":"SoQLText",
        "position":18,
        "input_schema_id":9649,
        "id":310281,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLFloatingTimestamp",
        "field_name":"updated_on"
      },
      {
        "soql_type":"SoQLText",
        "position":19,
        "input_schema_id":9649,
        "id":310282,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"latitude"
      },
      {
        "soql_type":"SoQLText",
        "position":20,
        "input_schema_id":9649,
        "id":310283,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLNumber",
        "field_name":"longitude"
      },
      {
        "soql_type":"SoQLText",
        "position":21,
        "input_schema_id":9649,
        "id":310284,
        "guessed_subtypes":[

        ],
        "guessed_soql_type":"SoQLText",
        "field_name":"location"
      }
    ],
    "id":9649,
    "created_by":{
      "user_id":"k7tm-2kym",
      "email":"test.user@socrata.com",
      "display_name":"Test User"
    }
  },
  "links":{
    "transform":"/api/publishing/v1/upload/8325/schema/9649",
    "show":"/api/publishing/v1/upload/8325/schema/9649",
    "latest_output":"/api/publishing/v1/upload/8325/schema/9649/output/latest"
  }
};

export const uploadShow = {
  "resource":{
    "schemas":[],
    "inserted_at":"2017-05-09T23:10:16.339627",
    "id":8325,
    "finished_at":null,
    "filename":"petty_crimes.csv",
    "failed_at":null,
    "created_by":{
      "user_id":"k7tm-2kym",
      "email":"test.user@socrata.com",
      "display_name":"Test User"
    },
    "content_type":null
  },
  "links":{
    "show":"/api/publishing/v1/upload/8325",
    "bytes":"/api/publishing/v1/upload/8325",
    "add_to_revision":"/api/publishing/v1/upload/8325"
  }
};
